import { useCallback, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { supabase } from '@/integrations/supabase/client';
import BudgetCalculator from '@/pages/dashboard/lfa-builder/BudgetCalculator';
import { ProjectWorkspaceNav } from '../ProjectWorkspaceNav';

/**
 * PM-2 scope only: thin wrapper resolving projectId -> orgId and rendering
 * the existing BudgetCalculator unchanged -- it already has zero lfa_entries
 * dependency and fetches Level 2 WBS activities purely by lfa_project_id, so
 * manual WBS creation (Project Management) needs no BudgetCalculator change
 * at all. The only addition here is a read-only Stage Budget summary,
 * derived Budget Item -> WBS Item -> Stage, computed in this wrapper without
 * touching lfa_budget_items or BudgetCalculator's own totals.
 */
interface StageOption {
  id: string;
  title: string;
}

interface StageSummaryRow {
  stageId: string | null;
  title: string;
  total: number;
}

export default function ProjectBudgetPage() {
  const { projectId } = useParams<{ projectId: string }>();
  const navigate = useNavigate();

  const [orgId, setOrgId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [stageSummary, setStageSummary] = useState<StageSummaryRow[]>([]);

  const loadStageSummary = useCallback(async () => {
    if (!projectId) return;
    try {
      const [wbsRes, budgetRes, stagesRes] = await Promise.all([
        // stage_id is not yet reflected in the generated Database type
        // (types are Production-canonical and are not regenerated by this
        // change), so this one query is narrowly cast.
        (supabase as any)
          .from('lfa_wbs_items')
          .select('id, level, parent_id, stage_id')
          .eq('lfa_project_id', projectId),
        supabase
          .from('lfa_budget_items')
          .select('id, wbs_item_id, volume, unit_price_idr')
          .eq('lfa_project_id', projectId),
        (supabase as any).from('project_stages').select('id, title').eq('project_id', projectId),
      ]);

      if (wbsRes.error) throw wbsRes.error;
      if (budgetRes.error) throw budgetRes.error;
      if (stagesRes.error) throw stagesRes.error;

      const wbsById = new Map<string, { level: number; parent_id: string | null; stage_id: string | null }>(
        (wbsRes.data || []).map((w) => [w.id, w]),
      );
      const stages = (stagesRes.data || []) as StageOption[];
      const stageTitleById = new Map(stages.map((s) => [s.id, s.title]));

      // Budget Item -> WBS Item -> walk up parent_id to the Level 1
      // ancestor -> that ancestor's stage_id. One walk per budget item, so
      // each item contributes to exactly one bucket -- no double-count.
      const findLevel1StageId = (wbsItemId: string | null): string | null => {
        if (!wbsItemId) return null;
        let current = wbsById.get(wbsItemId);
        let guard = 0;
        while (current && current.level !== 1 && current.parent_id && guard < 10) {
          current = wbsById.get(current.parent_id);
          guard += 1;
        }
        return current?.stage_id ?? null;
      };

      const totals = new Map<string | null, number>();
      for (const item of budgetRes.data || []) {
        const amount = (Number(item.volume) || 0) * (Number(item.unit_price_idr) || 0);
        const stageId = findLevel1StageId(item.wbs_item_id);
        totals.set(stageId, (totals.get(stageId) || 0) + amount);
      }

      const rows: StageSummaryRow[] = [];
      for (const stage of stages) {
        rows.push({ stageId: stage.id, title: stage.title, total: totals.get(stage.id) || 0 });
      }
      rows.push({ stageId: null, title: 'Unassigned', total: totals.get(null) || 0 });
      setStageSummary(rows);
    } catch (err) {
      console.error('[Impactory] Error computing stage budget summary:', err);
    }
  }, [projectId]);

  useEffect(() => {
    if (!projectId) return;
    setLoading(true);
    setError(null);
    supabase
      .from('lfa_projects')
      .select('org_id')
      .eq('id', projectId)
      .single()
      .then(({ data, error: fetchError }) => {
        if (fetchError) {
          setError(fetchError.message);
        } else {
          setOrgId(data?.org_id ?? null);
        }
        setLoading(false);
      });
    void loadStageSummary();
  }, [projectId, loadStageSummary]);

  const formatIDR = (n: number) => `Rp ${n.toLocaleString('id-ID')}`;

  return (
    <div className="mx-auto max-w-6xl space-y-6 py-2">
      <div className="flex items-center gap-3">
        <Button variant="ghost" size="sm" onClick={() => navigate('/dashboard/project-management')}>
          <ArrowLeft className="mr-2 h-4 w-4" />
          Kembali
        </Button>
      </div>

      {projectId && <ProjectWorkspaceNav projectId={projectId} />}

      {loading ? (
        <div className="flex items-center justify-center py-16 text-muted-foreground">
          <Loader2 className="h-6 w-6 animate-spin" />
        </div>
      ) : error || !orgId || !projectId ? (
        <Card className="border-destructive/50">
          <CardContent className="py-4 text-sm text-destructive">{error || 'Proyek tidak ditemukan.'}</CardContent>
        </Card>
      ) : (
        <>
          {stageSummary.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle className="text-base">Ringkasan Budget per Stage</CardTitle>
                <CardDescription>
                  Diturunkan dari Budget Item → WBS Item → Stage. Item WBS yang belum ditautkan ke
                  Stage muncul di baris Unassigned.
                </CardDescription>
              </CardHeader>
              <CardContent className="grid grid-cols-2 gap-3 sm:grid-cols-3">
                {stageSummary.map((row) => (
                  <div key={row.stageId ?? 'unassigned'} className="rounded-md border p-3">
                    <div className="text-xs text-muted-foreground">{row.title}</div>
                    <div className="text-sm font-bold">{formatIDR(row.total)}</div>
                  </div>
                ))}
              </CardContent>
            </Card>
          )}
          <BudgetCalculator projectId={projectId} orgId={orgId} onBudgetChanged={() => void loadStageSummary()} />
        </>
      )}
    </div>
  );
}
