import type { Grant } from './types';

/**
 * Mock grant database — 28 entries blending real-world donor archetypes
 * (Ford Foundation, Tanoto, Bakti Barito, Hivos, GIZ, etc.) with realistic
 * Indonesian focus areas. Replace with live data when a backend is wired.
 * NOTE: All amounts in IDR; deadlines are forward-looking (current era ~2026).
 */
export const MOCK_GRANTS: Grant[] = [
  {
    id: 'gf-001',
    donor: 'Ford Foundation Indonesia',
    title: 'Building Institutions and Networks (BUILD) — Indonesia 2026',
    origin: 'internasional',
    sdgs: [10, 16, 17],
    sectors: ['tata_kelola', 'gender'],
    geography: ['nasional'],
    amountMinIdr: 1_500_000_000,
    amountMaxIdr: 7_500_000_000,
    deadline: '2026-07-31',
    eligibleStages: ['berkembang', 'mapan'],
    summary:
      'Hibah multi-tahun untuk memperkuat kapasitas institusional CSO yang bekerja pada keadilan sosial dan inklusi.',
    eligibility: [
      'Berbentuk yayasan/perkumpulan terdaftar minimal 5 tahun',
      'Audited financials 3 tahun terakhir',
      'Fokus pada keadilan sosial, gender, atau tata kelola',
    ],
    requirements: [
      'Concept note 5 halaman',
      'Theory of Change',
      'Budget naratif & itemized',
      'Letter of intent dari board',
    ],
    applicationUrl: 'https://www.fordfoundation.org/work/our-grants/',
    donorWebsite: 'https://www.fordfoundation.org',
    recurring: true,
  },
  {
    id: 'gf-002',
    donor: 'Tanoto Foundation',
    title: 'Pintar — Penguatan Pendidikan Dasar Berkualitas',
    origin: 'lokal',
    sdgs: [4, 17],
    sectors: ['pendidikan'],
    geography: ['sumatera', 'jawa', 'kalimantan'],
    amountMinIdr: 250_000_000,
    amountMaxIdr: 1_500_000_000,
    deadline: '2026-05-30',
    eligibleStages: ['rintisan', 'berkembang', 'mapan'],
    summary:
      'Mendukung program peningkatan kualitas pendidikan dasar dan pengembangan profesional guru di daerah prioritas.',
    eligibility: [
      'Lembaga pendidikan / NGO pendidikan',
      'Memiliki kemitraan dengan dinas pendidikan setempat',
    ],
    requirements: ['Proposal naratif', 'RAB rinci', 'MoU pemerintah daerah'],
    applicationUrl: 'https://www.tanotofoundation.org',
    donorWebsite: 'https://www.tanotofoundation.org',
  },
  {
    id: 'gf-003',
    donor: 'Bakti Barito Foundation',
    title: 'Hibah Konservasi Hutan & Komunitas Adat',
    origin: 'korporat',
    sdgs: [13, 15],
    sectors: ['lingkungan'],
    geography: ['kalimantan', 'maluku_papua'],
    amountMinIdr: 500_000_000,
    amountMaxIdr: 3_000_000_000,
    deadline: '2026-06-15',
    eligibleStages: ['berkembang', 'mapan'],
    summary:
      'Pendanaan konservasi hutan tropis berbasis komunitas, agroforestry, dan livelihood masyarakat adat.',
    eligibility: [
      'Pengalaman kerja 3+ tahun di wilayah hutan',
      'Memiliki kemitraan dengan masyarakat adat',
    ],
    requirements: ['Concept note', 'Peta wilayah kerja', 'FPIC document'],
    applicationUrl: 'https://www.baktibarito.org',
  },
  {
    id: 'gf-004',
    donor: 'Hivos Southeast Asia',
    title: 'Voices for Just Climate Action — Indonesia',
    origin: 'internasional',
    sdgs: [7, 13],
    sectors: ['lingkungan', 'energi'],
    geography: ['nasional'],
    amountMinIdr: 800_000_000,
    amountMaxIdr: 4_000_000_000,
    deadline: '2026-05-12',
    eligibleStages: ['rintisan', 'berkembang', 'mapan'],
    summary:
      'Memperkuat suara komunitas lokal dalam advokasi transisi energi adil dan aksi iklim.',
    eligibility: ['CSO/koalisi lokal', 'Track record advokasi iklim'],
    requirements: ['Concept note 3 hal', 'Budget summary', 'Partner letters'],
    applicationUrl: 'https://hivos.org/program/voices-for-just-climate-action/',
    donorWebsite: 'https://hivos.org',
  },
  {
    id: 'gf-005',
    donor: 'GIZ Indonesia',
    title: 'Innovation Fund Energi Terbarukan Pulau-Pulau Kecil',
    origin: 'multilateral',
    sdgs: [7, 9, 13],
    sectors: ['energi', 'teknologi'],
    geography: ['bali_nt', 'sulawesi', 'maluku_papua'],
    amountMinIdr: 1_000_000_000,
    amountMaxIdr: 5_000_000_000,
    deadline: '2026-08-20',
    eligibleStages: ['rintisan', 'berkembang', 'mapan'],
    summary:
      'Skema co-funding untuk pilot teknologi energi terbarukan off-grid di pulau-pulau kecil Indonesia Timur.',
    eligibility: ['Konsorsium NGO + technical partner', 'Cost-share minimal 20%'],
    requirements: ['Pitch deck teknis', 'Feasibility study ringkas', 'Co-funding letter'],
    applicationUrl: 'https://www.giz.de/en/worldwide/33223.html',
  },
  {
    id: 'gf-006',
    donor: 'UNICEF Indonesia',
    title: 'WASH in Schools — Mitra Implementasi 2026',
    origin: 'multilateral',
    sdgs: [3, 4, 6],
    sectors: ['air_sanitasi', 'pendidikan', 'kesehatan'],
    geography: ['nasional'],
    amountMinIdr: 400_000_000,
    amountMaxIdr: 2_500_000_000,
    deadline: '2026-05-05',
    eligibleStages: ['berkembang', 'mapan'],
    summary:
      'Pengadaan sarana air bersih, sanitasi, dan promosi higiene di sekolah dasar daerah tertinggal.',
    eligibility: ['Terdaftar di sistem mitra UN', 'Audit eksternal tersedia'],
    requirements: ['Workplan', 'Logframe', 'M&E plan'],
    applicationUrl: 'https://www.unicef.org/indonesia/partnerships',
  },
  {
    id: 'gf-007',
    donor: 'Yayasan KEHATI',
    title: 'TFCA Sumatera — Hibah Konservasi Hutan',
    origin: 'lokal',
    sdgs: [13, 15],
    sectors: ['lingkungan'],
    geography: ['sumatera'],
    amountMinIdr: 300_000_000,
    amountMaxIdr: 2_000_000_000,
    deadline: '2026-06-30',
    eligibleStages: ['rintisan', 'berkembang', 'mapan'],
    summary:
      'Tropical Forest Conservation Action — pendanaan konservasi keanekaragaman hayati Sumatera.',
    eligibility: ['Berbasis di Sumatera', 'Berbadan hukum'],
    requirements: ['Proposal lengkap', 'Peta intervensi', 'RAB'],
    applicationUrl: 'https://www.kehati.or.id',
    donorWebsite: 'https://www.kehati.or.id',
    recurring: true,
  },
  {
    id: 'gf-008',
    donor: 'DFAT Australia (Australia Awards)',
    title: 'Skala Initiative — Local Development Innovation',
    origin: 'internasional',
    sdgs: [1, 8, 10],
    sectors: ['ekonomi', 'tata_kelola'],
    geography: ['nasional'],
    amountMinIdr: 600_000_000,
    amountMaxIdr: 3_500_000_000,
    deadline: '2026-07-15',
    eligibleStages: ['berkembang', 'mapan'],
    summary:
      'Mendukung inovasi pemerintah daerah dan CSO untuk percepatan pembangunan kawasan timur Indonesia.',
    eligibility: ['CSO Indonesia', 'Kerja di Indonesia Timur diutamakan'],
    requirements: ['EOI', 'Full proposal jika lolos', 'Risk assessment'],
    applicationUrl: 'https://www.skala.or.id',
  },
  {
    id: 'gf-009',
    donor: 'PT Astra International — Yayasan Astra',
    title: 'Kampung Berseri Astra — Replikasi 2026',
    origin: 'korporat',
    sdgs: [3, 4, 8, 11],
    sectors: ['ekonomi', 'kesehatan', 'pendidikan'],
    geography: ['nasional'],
    amountMinIdr: 100_000_000,
    amountMaxIdr: 500_000_000,
    deadline: '2026-09-30',
    eligibleStages: ['inisiatif', 'rintisan', 'berkembang'],
    summary:
      'Pengembangan kampung berkelanjutan dengan empat pilar: kesehatan, pendidikan, lingkungan, dan kewirausahaan.',
    eligibility: ['Kelompok masyarakat / NGO lokal', 'Kemitraan dengan kelurahan'],
    requirements: ['Proposal singkat', 'Profil kampung', 'RAB'],
    applicationUrl: 'https://www.astra.co.id/CSR',
    recurring: true,
  },
  {
    id: 'gf-010',
    donor: 'European Union — EIDHR',
    title: 'European Instrument for Democracy & Human Rights',
    origin: 'multilateral',
    sdgs: [5, 10, 16],
    sectors: ['tata_kelola', 'gender', 'kemanusiaan'],
    geography: ['nasional'],
    amountMinIdr: 2_000_000_000,
    amountMaxIdr: 8_000_000_000,
    deadline: '2026-06-08',
    eligibleStages: ['berkembang', 'mapan'],
    summary:
      'Hibah HAM dan demokrasi untuk CSO yang melindungi hak-hak kelompok rentan dan kebebasan sipil.',
    eligibility: ['CSO terdaftar 5+ tahun', 'Kapasitas keuangan >Rp 2 M/tahun'],
    requirements: ['Concept note EU template', 'Logframe', 'PADOR registration'],
    applicationUrl: 'https://international-partnerships.ec.europa.eu',
  },
  {
    id: 'gf-011',
    donor: 'Mastercard Foundation',
    title: 'Young Africa Works — SE Asia Pilot (Indonesia)',
    origin: 'internasional',
    sdgs: [4, 5, 8],
    sectors: ['ekonomi', 'pendidikan'],
    geography: ['nasional'],
    amountMinIdr: 3_000_000_000,
    amountMaxIdr: 15_000_000_000,
    deadline: '2026-10-31',
    eligibleStages: ['mapan'],
    summary:
      'Program berskala besar untuk peningkatan akses kerja layak bagi pemuda, khususnya perempuan muda.',
    eligibility: ['Track record program ketenagakerjaan pemuda', 'Reach >10.000 beneficiaries'],
    requirements: ['Full proposal', 'Theory of Change', 'Audited reports 3 tahun'],
    applicationUrl: 'https://mastercardfdn.org',
  },
  {
    id: 'gf-012',
    donor: 'Bank Indonesia — Program Sosial Bank Indonesia',
    title: 'PSBI Pemberdayaan UMKM Klaster',
    origin: 'lokal',
    sdgs: [1, 8, 10],
    sectors: ['ekonomi'],
    geography: ['nasional'],
    amountMinIdr: 50_000_000,
    amountMaxIdr: 500_000_000,
    deadline: '2026-05-20',
    eligibleStages: ['inisiatif', 'rintisan', 'berkembang'],
    summary:
      'Pendanaan klaster UMKM unggulan daerah dengan pendekatan pemberdayaan ekonomi inklusif.',
    eligibility: ['Koperasi / kelompok UMKM', 'Berdomisili di wilayah kerja KPwBI'],
    requirements: ['Proposal singkat', 'Profil kelompok', 'RAB'],
    applicationUrl: 'https://www.bi.go.id',
    recurring: true,
  },
  {
    id: 'gf-013',
    donor: 'Global Fund for Women',
    title: 'Crisis Fund — Mendesak untuk Kelompok Perempuan',
    origin: 'internasional',
    sdgs: [5, 10, 16],
    sectors: ['gender'],
    geography: ['nasional'],
    amountMinIdr: 75_000_000,
    amountMaxIdr: 450_000_000,
    deadline: '2026-12-31',
    eligibleStages: ['inisiatif', 'rintisan', 'berkembang', 'mapan'],
    summary:
      'Hibah cepat untuk respon terhadap krisis yang berdampak pada perempuan, anak perempuan, dan trans.',
    eligibility: ['Dipimpin oleh perempuan/trans', 'Fokus pada hak perempuan'],
    requirements: ['Aplikasi singkat online'],
    applicationUrl: 'https://www.globalfundforwomen.org/apply-for-a-grant/',
    recurring: true,
  },
  {
    id: 'gf-014',
    donor: 'IFAD',
    title: 'Rural Empowerment & Agricultural Development Indonesia',
    origin: 'multilateral',
    sdgs: [1, 2, 8],
    sectors: ['pertanian', 'ekonomi'],
    geography: ['sulawesi', 'maluku_papua'],
    amountMinIdr: 2_500_000_000,
    amountMaxIdr: 10_000_000_000,
    deadline: '2026-08-31',
    eligibleStages: ['berkembang', 'mapan'],
    summary:
      'Pengembangan rantai nilai pertanian inklusif di kawasan Indonesia Timur untuk petani kecil.',
    eligibility: ['Konsorsium dengan koperasi tani', 'Pengalaman value chain'],
    requirements: ['Concept note', 'Value chain map', 'M&E framework'],
    applicationUrl: 'https://www.ifad.org/en/web/operations/w/country/indonesia',
  },
  {
    id: 'gf-015',
    donor: 'Yayasan Pulse Lab Jakarta',
    title: 'Tech for Good Innovation Grant',
    origin: 'lokal',
    sdgs: [9, 10, 17],
    sectors: ['teknologi'],
    geography: ['nasional'],
    amountMinIdr: 150_000_000,
    amountMaxIdr: 750_000_000,
    deadline: '2026-05-25',
    eligibleStages: ['inisiatif', 'rintisan'],
    summary:
      'Mendukung startup sosial dan civic-tech yang menggunakan data untuk dampak sosial.',
    eligibility: ['Tim teknis aktif', 'Prototype atau MVP'],
    requirements: ['Pitch deck', 'Demo produk', 'Roadmap'],
    applicationUrl: 'https://pulselabjakarta.org',
  },
  {
    id: 'gf-016',
    donor: 'World Bank — Japan Social Development Fund',
    title: 'JSDF Community-Driven Development Indonesia',
    origin: 'multilateral',
    sdgs: [1, 11, 16],
    sectors: ['tata_kelola', 'ekonomi'],
    geography: ['nasional'],
    amountMinIdr: 4_000_000_000,
    amountMaxIdr: 20_000_000_000,
    deadline: '2026-09-15',
    eligibleStages: ['mapan'],
    summary:
      'Hibah berskala besar untuk replikasi model pembangunan partisipatif berbasis masyarakat.',
    eligibility: ['Endorsement Bappenas', 'Kapasitas implementasi >Rp 10 M/tahun'],
    requirements: ['Concept note', 'Government endorsement letter', 'Procurement plan'],
    applicationUrl: 'https://www.worldbank.org/en/programs/japan-social-development-fund',
  },
  {
    id: 'gf-017',
    donor: 'Yayasan Indonesia untuk Kemanusiaan (YIK)',
    title: 'Hibah Respons Bencana & Kemanusiaan',
    origin: 'lokal',
    sdgs: [1, 11, 13],
    sectors: ['kemanusiaan'],
    geography: ['nasional'],
    amountMinIdr: 50_000_000,
    amountMaxIdr: 300_000_000,
    deadline: '2026-12-31',
    eligibleStages: ['inisiatif', 'rintisan', 'berkembang'],
    summary:
      'Pendanaan cepat untuk respons darurat dan recovery komunitas pasca bencana.',
    eligibility: ['Lembaga lokal di wilayah terdampak', 'Bisa mobilisasi dalam 7 hari'],
    requirements: ['Aplikasi singkat', 'Assessment cepat'],
    applicationUrl: 'https://yik.or.id',
    recurring: true,
  },
  {
    id: 'gf-018',
    donor: 'Djarum Foundation',
    title: 'Bakti Pendidikan Beasiswa Plus 2026',
    origin: 'korporat',
    sdgs: [4],
    sectors: ['pendidikan'],
    geography: ['nasional'],
    amountMinIdr: 200_000_000,
    amountMaxIdr: 1_000_000_000,
    deadline: '2026-06-25',
    eligibleStages: ['rintisan', 'berkembang', 'mapan'],
    summary:
      'Program beasiswa dan capacity building untuk mahasiswa berprestasi dari keluarga kurang mampu.',
    eligibility: ['Lembaga pendidikan / yayasan beasiswa'],
    requirements: ['Proposal program', 'Daftar calon penerima manfaat'],
    applicationUrl: 'https://djarumfoundation.org',
  },
  {
    id: 'gf-019',
    donor: 'Climate Justice Resilience Fund',
    title: 'CJRF Asia — Solusi Iklim Berbasis Komunitas',
    origin: 'internasional',
    sdgs: [13, 14, 15],
    sectors: ['lingkungan'],
    geography: ['nasional', 'asia_tenggara'],
    amountMinIdr: 700_000_000,
    amountMaxIdr: 3_500_000_000,
    deadline: '2026-07-10',
    eligibleStages: ['berkembang', 'mapan'],
    summary:
      'Hibah multi-tahun untuk solusi adaptasi iklim yang dipimpin perempuan, pemuda, dan masyarakat adat.',
    eligibility: ['Dipimpin oleh kelompok terdampak iklim', 'Pendekatan berbasis hak'],
    requirements: ['Concept note', 'Budget naratif', 'Reference letters'],
    applicationUrl: 'https://www.cjrfund.org',
  },
  {
    id: 'gf-020',
    donor: 'BUMN — PT Pertamina (Persero)',
    title: 'Pertamina Sehati & Desa Energi Berdikari',
    origin: 'korporat',
    sdgs: [3, 7, 11],
    sectors: ['kesehatan', 'energi'],
    geography: ['nasional'],
    amountMinIdr: 100_000_000,
    amountMaxIdr: 800_000_000,
    deadline: '2026-05-15',
    eligibleStages: ['rintisan', 'berkembang'],
    summary:
      'Program TJSL Pertamina untuk kesehatan ibu-anak dan kemandirian energi desa.',
    eligibility: ['NGO / kelompok masyarakat di sekitar wilayah operasi'],
    requirements: ['Proposal singkat', 'Surat dukungan pemerintah desa'],
    applicationUrl: 'https://www.pertamina.com',
  },
  {
    id: 'gf-021',
    donor: 'Pew Charitable Trusts',
    title: 'Marine Conservation Indonesia',
    origin: 'internasional',
    sdgs: [14],
    sectors: ['lingkungan'],
    geography: ['bali_nt', 'sulawesi', 'maluku_papua'],
    amountMinIdr: 1_200_000_000,
    amountMaxIdr: 6_000_000_000,
    deadline: '2026-08-05',
    eligibleStages: ['berkembang', 'mapan'],
    summary:
      'Mendukung perluasan kawasan konservasi laut, pengelolaan perikanan berkelanjutan, dan reformasi kebijakan kelautan.',
    eligibility: ['Track record konservasi laut 5+ tahun'],
    requirements: ['Letter of inquiry', 'Full proposal jika diminta'],
    applicationUrl: 'https://www.pewtrusts.org',
  },
  {
    id: 'gf-022',
    donor: 'Yayasan Belantara',
    title: 'Hibah Restorasi Lanskap & Mitigasi Konflik Satwa',
    origin: 'lokal',
    sdgs: [13, 15],
    sectors: ['lingkungan'],
    geography: ['sumatera', 'kalimantan'],
    amountMinIdr: 200_000_000,
    amountMaxIdr: 1_500_000_000,
    deadline: '2026-06-20',
    eligibleStages: ['rintisan', 'berkembang'],
    summary:
      'Pendanaan restorasi lanskap kritis dan mitigasi konflik manusia-gajah/orangutan.',
    eligibility: ['Berbasis di Sumatera atau Kalimantan'],
    requirements: ['Concept note', 'Peta intervensi'],
    applicationUrl: 'https://www.belantara.or.id',
  },
  {
    id: 'gf-023',
    donor: 'YAPPIKA-ActionAid',
    title: 'Hibah Penguatan CSO Akar Rumput',
    origin: 'lokal',
    sdgs: [10, 16, 17],
    sectors: ['tata_kelola', 'gender'],
    geography: ['nasional'],
    amountMinIdr: 30_000_000,
    amountMaxIdr: 200_000_000,
    deadline: '2026-05-08',
    eligibleStages: ['inisiatif', 'rintisan'],
    summary:
      'Hibah kecil untuk organisasi akar rumput yang mengadvokasi hak-hak warga dan pelayanan publik.',
    eligibility: ['Organisasi akar rumput', 'Belum pernah menerima hibah >Rp 500 jt'],
    requirements: ['Aplikasi singkat 3 hal', 'Profil organisasi'],
    applicationUrl: 'https://yappika-actionaid.or.id',
  },
  {
    id: 'gf-024',
    donor: 'GIZ — Cultural Preservation Fund',
    title: 'Warisan Budaya Tak Benda Nusantara',
    origin: 'multilateral',
    sdgs: [4, 11, 17],
    sectors: ['kebudayaan'],
    geography: ['nasional'],
    amountMinIdr: 250_000_000,
    amountMaxIdr: 1_200_000_000,
    deadline: '2026-07-25',
    eligibleStages: ['rintisan', 'berkembang', 'mapan'],
    summary:
      'Pelestarian dan revitalisasi warisan budaya tak benda dengan pelibatan generasi muda.',
    eligibility: ['Komunitas budaya / NGO budaya'],
    requirements: ['Proposal program', 'Dokumentasi budaya yang dilestarikan'],
    applicationUrl: 'https://www.giz.de/en/worldwide/33223.html',
  },
  {
    id: 'gf-025',
    donor: 'Open Society Foundations',
    title: 'OSF Asia Pacific — Justice & Accountability',
    origin: 'internasional',
    sdgs: [10, 16],
    sectors: ['tata_kelola'],
    geography: ['nasional', 'asia_tenggara'],
    amountMinIdr: 1_500_000_000,
    amountMaxIdr: 7_000_000_000,
    deadline: '2026-09-01',
    eligibleStages: ['berkembang', 'mapan'],
    summary:
      'Mendukung CSO yang memperjuangkan keadilan, akuntabilitas pemerintah, dan kebebasan media.',
    eligibility: ['CSO terdaftar', 'Track record advokasi'],
    requirements: ['Concept note by invitation'],
    applicationUrl: 'https://www.opensocietyfoundations.org',
  },
  {
    id: 'gf-026',
    donor: 'Yayasan WINGS Peduli',
    title: 'Hibah Air Bersih & Sanitasi Sekolah',
    origin: 'korporat',
    sdgs: [3, 6],
    sectors: ['air_sanitasi', 'kesehatan'],
    geography: ['jawa', 'sumatera', 'sulawesi'],
    amountMinIdr: 75_000_000,
    amountMaxIdr: 350_000_000,
    deadline: '2026-05-18',
    eligibleStages: ['inisiatif', 'rintisan', 'berkembang'],
    summary:
      'Pembangunan sarana air bersih dan toilet sekolah di daerah dengan akses sanitasi rendah.',
    eligibility: ['NGO atau yayasan pendidikan'],
    requirements: ['Proposal singkat', 'Foto baseline lokasi'],
    applicationUrl: 'https://www.wingscorp.com',
  },
  {
    id: 'gf-027',
    donor: 'Asia Foundation Indonesia',
    title: 'Local Governance Innovation Fund',
    origin: 'internasional',
    sdgs: [11, 16, 17],
    sectors: ['tata_kelola', 'teknologi'],
    geography: ['nasional'],
    amountMinIdr: 400_000_000,
    amountMaxIdr: 2_000_000_000,
    deadline: '2026-07-05',
    eligibleStages: ['rintisan', 'berkembang', 'mapan'],
    summary:
      'Inovasi tata kelola lokal untuk pelayanan publik yang lebih responsif, transparan, dan inklusif.',
    eligibility: ['CSO atau lembaga riset', 'Kemitraan dengan pemda'],
    requirements: ['Concept note', 'Letter of support pemda'],
    applicationUrl: 'https://asiafoundation.org/where-we-work/indonesia/',
  },
  {
    id: 'gf-028',
    donor: 'Yayasan Plan International Indonesia',
    title: 'Hibah Inklusi Anak Perempuan & Pemuda',
    origin: 'internasional',
    sdgs: [4, 5, 10],
    sectors: ['gender', 'pendidikan'],
    geography: ['bali_nt', 'sulawesi'],
    amountMinIdr: 300_000_000,
    amountMaxIdr: 1_500_000_000,
    deadline: '2026-08-15',
    eligibleStages: ['rintisan', 'berkembang'],
    summary:
      'Mendukung program pendidikan, kepemimpinan, dan perlindungan anak perempuan di NTT dan Sulawesi.',
    eligibility: ['NGO lokal di wilayah sasaran'],
    requirements: ['Proposal lengkap', 'Child safeguarding policy'],
    applicationUrl: 'https://plan-international.or.id',
  },
];