import { useCallback, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowDown, ArrowUp, ChevronDown, ListTodo, Loader2, Plus, RotateCcw, Trash2, Waypoints } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import { useOrgRole } from '@/hooks/useOrgRole';
import { ProjectWorkspaceNav } from '../ProjectWorkspaceNav';

/**
 * PM-1C scope only: Stage CRUD/reorder/archive/restore via RPC, plus a
 * primary-Objective picker. All mutation calls create_project_stage /
 * update_project_stage_metadata / reorder_project_stages /
 * archive_project_stage / restore_project_stage -- never a direct table
 * write. WBS/Budget/MEAL/Deliverables workspace views land in later phases.
 */
interface Stage {
  id: string;
  title: string;
  description: string | null;
  primary_objective_id: string | null;
  status: 'not_started' | 'in_progress' | 'completed' | 'archived';
  sort_order: number;
  planned_start_date: string | null;
  planned_end_date: string | null;
  actual_start_date: string | null;
  actual_end_date: string | null;
  archived_at: string | null;
}

interface ObjectiveOption {
  id: string;
  title: string;
  archived_at: string | null;
}

const NO_OBJECTIVE = '__none__';

export default function ProjectStagesPage() {
  const { projectId } = useParams<{ projectId: string }>();
  const navigate = useNavigate();
  const { toast } = useToast();
  const { canDelete } = useOrgRole();

  const [stages, setStages] = useState<Stage[]>([]);
  const [objectives, setObjectives] = useState<ObjectiveOption[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [createOpen, setCreateOpen] = useState(false);
  const [editing, setEditing] = useState<Stage | null>(null);
  const [saving, setSaving] = useState(false);

  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [primaryObjectiveId, setPrimaryObjectiveId] = useState<string>(NO_OBJECTIVE);
  const [status, setStatus] = useState<'not_started' | 'in_progress' | 'completed'>('not_started');
  const [plannedStart, setPlannedStart] = useState('');
  const [plannedEnd, setPlannedEnd] = useState('');
  const [actualStart, setActualStart] = useState('');
  const [actualEnd, setActualEnd] = useState('');
  const [advancedOpen, setAdvancedOpen] = useState(false);

  const loadData = useCallback(async () => {
    if (!projectId) return;
    setLoading(true);
    setError(null);
    try {
      // project_stages/project_objectives are not yet reflected in the
      // generated Database type (types are Production-canonical and are not
      // regenerated by this change), so these two queries are narrowly cast.
      const [stagesRes, objectivesRes] = await Promise.all([
        (supabase as any)
          .from('project_stages')
          .select(
            'id, title, description, primary_objective_id, status, sort_order, planned_start_date, planned_end_date, actual_start_date, actual_end_date, archived_at',
          )
          .eq('project_id', projectId)
          .order('archived_at', { ascending: true, nullsFirst: true })
          .order('sort_order', { ascending: true }),
        (supabase as any)
          .from('project_objectives')
          .select('id, title, archived_at')
          .eq('project_id', projectId),
      ]);

      if (stagesRes.error) throw stagesRes.error;
      if (objectivesRes.error) throw objectivesRes.error;
      setStages((stagesRes.data || []) as Stage[]);
      setObjectives((objectivesRes.data || []) as ObjectiveOption[]);
    } catch (err) {
      const e = err as Error;
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }, [projectId]);

  useEffect(() => {
    void loadData();
  }, [loadData]);

  const resetForm = () => {
    setTitle('');
    setDescription('');
    setPrimaryObjectiveId(NO_OBJECTIVE);
    setStatus('not_started');
    setPlannedStart('');
    setPlannedEnd('');
    setActualStart('');
    setActualEnd('');
    setAdvancedOpen(false);
  };

  const openEdit = (stage: Stage) => {
    setEditing(stage);
    setTitle(stage.title);
    setDescription(stage.description || '');
    setPrimaryObjectiveId(stage.primary_objective_id || NO_OBJECTIVE);
    setStatus(stage.status === 'archived' ? 'not_started' : stage.status);
    setPlannedStart(stage.planned_start_date || '');
    setPlannedEnd(stage.planned_end_date || '');
    setActualStart(stage.actual_start_date || '');
    setActualEnd(stage.actual_end_date || '');
    // Existing Stages likely already carry some of these fields -- open the
    // advanced section by default when editing so nothing already set is
    // hidden from view, while a brand-new Stage still starts collapsed.
    setAdvancedOpen(Boolean(
      stage.description || stage.primary_objective_id || stage.planned_start_date || stage.planned_end_date,
    ));
  };

  const handleCreate = async () => {
    if (!title.trim() || !projectId) return;
    setSaving(true);
    try {
      const { error: rpcError } = await (supabase.rpc as any)('create_project_stage', {
        p_project_id: projectId,
        p_title: title.trim(),
        p_description: description || null,
        p_primary_objective_id: primaryObjectiveId === NO_OBJECTIVE ? null : primaryObjectiveId,
        p_planned_start_date: plannedStart || null,
        p_planned_end_date: plannedEnd || null,
      });
      if (rpcError) throw rpcError;

      toast({ title: 'Stage Ditambahkan' });
      setCreateOpen(false);
      resetForm();
      void loadData();
    } catch (err) {
      const e = err as Error;
      toast({ title: 'Gagal menambahkan Stage', description: e.message, variant: 'destructive' });
    } finally {
      setSaving(false);
    }
  };

  const handleUpdate = async () => {
    if (!editing || !title.trim()) return;
    setSaving(true);
    try {
      const { error: rpcError } = await (supabase.rpc as any)('update_project_stage_metadata', {
        p_stage_id: editing.id,
        p_title: title.trim(),
        p_description: description || null,
        p_primary_objective_id: primaryObjectiveId === NO_OBJECTIVE ? null : primaryObjectiveId,
        p_status: status,
        p_planned_start_date: plannedStart || null,
        p_planned_end_date: plannedEnd || null,
        p_actual_start_date: actualStart || null,
        p_actual_end_date: actualEnd || null,
      });
      if (rpcError) throw rpcError;

      toast({ title: 'Stage Diperbarui' });
      setEditing(null);
      resetForm();
      void loadData();
    } catch (err) {
      const e = err as Error;
      toast({ title: 'Gagal memperbarui Stage', description: e.message, variant: 'destructive' });
    } finally {
      setSaving(false);
    }
  };

  const handleArchive = async (stage: Stage) => {
    try {
      const { error: rpcError } = await (supabase.rpc as any)('archive_project_stage', { p_stage_id: stage.id });
      if (rpcError) throw rpcError;
      toast({ title: 'Stage Diarsipkan' });
      void loadData();
    } catch (err) {
      const e = err as Error;
      toast({ title: 'Gagal mengarsipkan Stage', description: e.message, variant: 'destructive' });
    }
  };

  const handleRestore = async (stage: Stage) => {
    try {
      const { error: rpcError } = await (supabase.rpc as any)('restore_project_stage', { p_stage_id: stage.id });
      if (rpcError) throw rpcError;
      toast({ title: 'Stage Dikembalikan' });
      void loadData();
    } catch (err) {
      const e = err as Error;
      toast({ title: 'Gagal mengembalikan Stage', description: e.message, variant: 'destructive' });
    }
  };

  const handleMove = async (index: number, direction: -1 | 1) => {
    const active = stages.filter((s) => !s.archived_at);
    const targetIndex = index + direction;
    if (targetIndex < 0 || targetIndex >= active.length || !projectId) return;

    const reordered = [...active];
    [reordered[index], reordered[targetIndex]] = [reordered[targetIndex], reordered[index]];
    const orderedIds = reordered.map((s) => s.id);

    try {
      const { error: rpcError } = await (supabase.rpc as any)('reorder_project_stages', {
        p_project_id: projectId,
        p_ordered_ids: orderedIds,
      });
      if (rpcError) throw rpcError;
      void loadData();
    } catch (err) {
      const e = err as Error;
      toast({ title: 'Gagal mengubah urutan', description: e.message, variant: 'destructive' });
    }
  };

  const activeStages = stages.filter((s) => !s.archived_at);
  const archivedStages = stages.filter((s) => s.archived_at);
  const objectiveTitle = (id: string | null) => objectives.find((o) => o.id === id)?.title;

  const statusVariant = (s: Stage['status']) =>
    s === 'completed' ? 'default' : s === 'in_progress' ? 'secondary' : 'outline';

  return (
    <div className="mx-auto max-w-4xl space-y-6 py-2">
      <div className="flex items-center gap-3">
        <Button variant="ghost" size="sm" onClick={() => navigate('/dashboard/project-management')}>
          <ArrowLeft className="mr-2 h-4 w-4" />
          Kembali
        </Button>
      </div>

      {projectId && <ProjectWorkspaceNav projectId={projectId} />}

      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Stages</h1>
          <p className="text-sm text-muted-foreground">Tahapan pelaksanaan proyek Project Management ini.</p>
        </div>
        <Button onClick={() => setCreateOpen(true)}>
          <Plus className="mr-2 h-4 w-4" />
          Stage Baru
        </Button>
      </div>

      {error && (
        <Card className="border-destructive/50">
          <CardContent className="py-4 text-sm text-destructive">{error}</CardContent>
        </Card>
      )}

      {loading ? (
        <div className="flex items-center justify-center py-16 text-muted-foreground">
          <Loader2 className="h-6 w-6 animate-spin" />
        </div>
      ) : activeStages.length === 0 ? (
        <Card>
          <CardContent className="flex flex-col items-center gap-3 py-16 text-center">
            <Waypoints className="h-10 w-10 text-muted-foreground" />
            <CardTitle className="text-lg">Belum ada Stage</CardTitle>
            <CardDescription>Tambahkan Stage pertama untuk proyek ini.</CardDescription>
            <Button onClick={() => setCreateOpen(true)} className="mt-2">
              <Plus className="mr-2 h-4 w-4" />
              Stage Baru
            </Button>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-3">
          {activeStages.map((stage, index) => (
            <Card key={stage.id}>
              <CardContent className="flex items-start justify-between gap-4 py-4">
                <div className="flex-1 space-y-1">
                  <div className="flex items-center gap-2">
                    <CardTitle className="text-base">{stage.title}</CardTitle>
                    <Badge variant={statusVariant(stage.status)}>{stage.status}</Badge>
                  </div>
                  {stage.description && <p className="text-sm text-muted-foreground">{stage.description}</p>}
                  {stage.primary_objective_id && (
                    <p className="text-xs text-muted-foreground">
                      Objective: {objectiveTitle(stage.primary_objective_id) || '(tidak diketahui)'}
                    </p>
                  )}
                  {(stage.planned_start_date || stage.planned_end_date) && (
                    <p className="text-xs text-muted-foreground">
                      Rencana: {stage.planned_start_date || '?'} — {stage.planned_end_date || '?'}
                    </p>
                  )}
                </div>
                <div className="flex shrink-0 items-center gap-1">
                  <Button variant="ghost" size="icon" disabled={index === 0} onClick={() => handleMove(index, -1)}>
                    <ArrowUp className="h-4 w-4" />
                  </Button>
                  <Button
                    variant="ghost"
                    size="icon"
                    disabled={index === activeStages.length - 1}
                    onClick={() => handleMove(index, 1)}
                  >
                    <ArrowDown className="h-4 w-4" />
                  </Button>
                  <Button
                    variant="secondary"
                    size="sm"
                    onClick={() => navigate(`/dashboard/project-management/${projectId}/wbs`)}
                  >
                    <ListTodo className="mr-1.5 h-4 w-4" />
                    Tambah Aktivitas
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => openEdit(stage)}>
                    Edit
                  </Button>
                  {canDelete && (
                    <Button variant="outline" size="icon" onClick={() => handleArchive(stage)}>
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {archivedStages.length > 0 && (
        <div className="space-y-3 pt-4">
          <h2 className="text-sm font-semibold text-muted-foreground">Diarsipkan</h2>
          {archivedStages.map((stage) => (
            <Card key={stage.id} className="opacity-70">
              <CardContent className="flex items-center justify-between gap-4 py-4">
                <div className="flex items-center gap-2">
                  <CardTitle className="text-base">{stage.title}</CardTitle>
                  <Badge variant="outline">archived</Badge>
                </div>
                {canDelete && (
                  <Button variant="outline" size="sm" onClick={() => handleRestore(stage)}>
                    <RotateCcw className="mr-2 h-4 w-4" />
                    Kembalikan
                  </Button>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      <Dialog
        open={createOpen || !!editing}
        onOpenChange={(open) => {
          if (!open) {
            setCreateOpen(false);
            setEditing(null);
            resetForm();
          }
        }}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{editing ? 'Edit Stage' : 'Stage Baru'}</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <Label htmlFor="stage-title">Judul Stage</Label>
              <Input
                id="stage-title"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                autoFocus
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && title.trim()) void (editing ? handleUpdate() : handleCreate());
                }}
              />
            </div>

            <Collapsible open={advancedOpen} onOpenChange={setAdvancedOpen}>
              <CollapsibleTrigger asChild>
                <Button variant="ghost" size="sm" className="-ml-2 text-xs text-muted-foreground">
                  <ChevronDown className={`mr-1.5 h-3.5 w-3.5 transition-transform ${advancedOpen ? 'rotate-180' : ''}`} />
                  Pengaturan Lanjutan
                </Button>
              </CollapsibleTrigger>
              <CollapsibleContent className="space-y-4 pt-3">
                <div>
                  <Label htmlFor="stage-desc">Deskripsi</Label>
                  <Textarea id="stage-desc" value={description} onChange={(e) => setDescription(e.target.value)} />
                </div>
                <div>
                  <Label htmlFor="stage-objective">Primary Objective</Label>
                  <Select value={primaryObjectiveId} onValueChange={setPrimaryObjectiveId}>
                    <SelectTrigger id="stage-objective">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value={NO_OBJECTIVE}>Tidak ada</SelectItem>
                      {objectives.map((o) => (
                        <SelectItem key={o.id} value={o.id}>
                          {o.title}
                          {o.archived_at ? ' (archived)' : ''}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="stage-planned-start">Rencana Mulai</Label>
                    <Input
                      id="stage-planned-start"
                      type="date"
                      value={plannedStart}
                      onChange={(e) => setPlannedStart(e.target.value)}
                    />
                  </div>
                  <div>
                    <Label htmlFor="stage-planned-end">Rencana Selesai</Label>
                    <Input
                      id="stage-planned-end"
                      type="date"
                      value={plannedEnd}
                      onChange={(e) => setPlannedEnd(e.target.value)}
                    />
                  </div>
                </div>
                {editing && (
                  <>
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <Label htmlFor="stage-actual-start">Aktual Mulai</Label>
                        <Input
                          id="stage-actual-start"
                          type="date"
                          value={actualStart}
                          onChange={(e) => setActualStart(e.target.value)}
                        />
                      </div>
                      <div>
                        <Label htmlFor="stage-actual-end">Aktual Selesai</Label>
                        <Input
                          id="stage-actual-end"
                          type="date"
                          value={actualEnd}
                          onChange={(e) => setActualEnd(e.target.value)}
                        />
                      </div>
                    </div>
                    <div>
                      <Label htmlFor="stage-status">Status</Label>
                      <Select value={status} onValueChange={(v) => setStatus(v as typeof status)}>
                        <SelectTrigger id="stage-status">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="not_started">Not Started</SelectItem>
                          <SelectItem value="in_progress">In Progress</SelectItem>
                          <SelectItem value="completed">Completed</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </>
                )}
              </CollapsibleContent>
            </Collapsible>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              disabled={saving}
              onClick={() => {
                setCreateOpen(false);
                setEditing(null);
                resetForm();
              }}
            >
              Batal
            </Button>
            <Button onClick={editing ? handleUpdate : handleCreate} disabled={saving || !title.trim()}>
              {saving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
              Simpan
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
