import { useCallback, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowDown, ArrowUp, Loader2, Plus, RotateCcw, Target, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import { useOrgRole } from '@/hooks/useOrgRole';
import { ProjectWorkspaceNav } from '../ProjectWorkspaceNav';

/**
 * PM-1B scope only: Objective CRUD/reorder/archive/restore via RPC. All
 * mutation calls create_project_objective / update_project_objective_metadata
 * / reorder_project_objectives / archive_project_objective /
 * restore_project_objective -- never a direct table write. Stage/WBS/Budget/
 * MEAL/Deliverables workspace views land in later PM phases.
 */
interface Objective {
  id: string;
  title: string;
  description: string | null;
  success_criteria: string | null;
  status: 'draft' | 'active' | 'completed' | 'archived';
  sort_order: number;
  archived_at: string | null;
}

export default function ProjectObjectivesPage() {
  const { projectId } = useParams<{ projectId: string }>();
  const navigate = useNavigate();
  const { toast } = useToast();
  const { canDelete } = useOrgRole();

  const [objectives, setObjectives] = useState<Objective[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [createOpen, setCreateOpen] = useState(false);
  const [editing, setEditing] = useState<Objective | null>(null);
  const [saving, setSaving] = useState(false);

  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [successCriteria, setSuccessCriteria] = useState('');
  const [status, setStatus] = useState<'draft' | 'active' | 'completed'>('draft');

  const loadObjectives = useCallback(async () => {
    if (!projectId) return;
    setLoading(true);
    setError(null);
    try {
      // project_objectives is not yet reflected in the generated Database
      // type (types are Production-canonical and are not regenerated by
      // this change), so this one query is narrowly cast.
      const { data, error: fetchError } = await (supabase as any).from('project_objectives')
        .select('id, title, description, success_criteria, status, sort_order, archived_at')
        .eq('project_id', projectId)
        .order('archived_at', { ascending: true, nullsFirst: true })
        .order('sort_order', { ascending: true });

      if (fetchError) throw fetchError;
      setObjectives((data || []) as Objective[]);
    } catch (err) {
      const e = err as Error;
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }, [projectId]);

  useEffect(() => {
    void loadObjectives();
  }, [loadObjectives]);

  const resetForm = () => {
    setTitle('');
    setDescription('');
    setSuccessCriteria('');
    setStatus('draft');
  };

  const openEdit = (objective: Objective) => {
    setEditing(objective);
    setTitle(objective.title);
    setDescription(objective.description || '');
    setSuccessCriteria(objective.success_criteria || '');
    setStatus(objective.status === 'archived' ? 'draft' : objective.status);
  };

  const handleCreate = async () => {
    if (!title.trim() || !projectId) return;
    setSaving(true);
    try {
      const { error: rpcError } = await (supabase.rpc as any)('create_project_objective', {
        p_project_id: projectId,
        p_title: title.trim(),
        p_description: description || null,
        p_success_criteria: successCriteria || null,
      });
      if (rpcError) throw rpcError;

      toast({ title: 'Objective Ditambahkan' });
      setCreateOpen(false);
      resetForm();
      void loadObjectives();
    } catch (err) {
      const e = err as Error;
      toast({ title: 'Gagal menambahkan Objective', description: e.message, variant: 'destructive' });
    } finally {
      setSaving(false);
    }
  };

  const handleUpdate = async () => {
    if (!editing || !title.trim()) return;
    setSaving(true);
    try {
      const { error: rpcError } = await (supabase.rpc as any)('update_project_objective_metadata', {
        p_objective_id: editing.id,
        p_title: title.trim(),
        p_description: description || null,
        p_success_criteria: successCriteria || null,
        p_status: status,
      });
      if (rpcError) throw rpcError;

      toast({ title: 'Objective Diperbarui' });
      setEditing(null);
      resetForm();
      void loadObjectives();
    } catch (err) {
      const e = err as Error;
      toast({ title: 'Gagal memperbarui Objective', description: e.message, variant: 'destructive' });
    } finally {
      setSaving(false);
    }
  };

  const handleArchive = async (objective: Objective) => {
    try {
      const { error: rpcError } = await (supabase.rpc as any)('archive_project_objective', {
        p_objective_id: objective.id,
      });
      if (rpcError) throw rpcError;
      toast({ title: 'Objective Diarsipkan' });
      void loadObjectives();
    } catch (err) {
      const e = err as Error;
      toast({ title: 'Gagal mengarsipkan Objective', description: e.message, variant: 'destructive' });
    }
  };

  const handleRestore = async (objective: Objective) => {
    try {
      const { error: rpcError } = await (supabase.rpc as any)('restore_project_objective', {
        p_objective_id: objective.id,
      });
      if (rpcError) throw rpcError;
      toast({ title: 'Objective Dikembalikan' });
      void loadObjectives();
    } catch (err) {
      const e = err as Error;
      toast({ title: 'Gagal mengembalikan Objective', description: e.message, variant: 'destructive' });
    }
  };

  const handleMove = async (index: number, direction: -1 | 1) => {
    const active = objectives.filter((o) => !o.archived_at);
    const targetIndex = index + direction;
    if (targetIndex < 0 || targetIndex >= active.length || !projectId) return;

    const reordered = [...active];
    [reordered[index], reordered[targetIndex]] = [reordered[targetIndex], reordered[index]];
    const orderedIds = reordered.map((o) => o.id);

    try {
      const { error: rpcError } = await (supabase.rpc as any)('reorder_project_objectives', {
        p_project_id: projectId,
        p_ordered_ids: orderedIds,
      });
      if (rpcError) throw rpcError;
      void loadObjectives();
    } catch (err) {
      const e = err as Error;
      toast({ title: 'Gagal mengubah urutan', description: e.message, variant: 'destructive' });
    }
  };

  const activeObjectives = objectives.filter((o) => !o.archived_at);
  const archivedObjectives = objectives.filter((o) => o.archived_at);

  const statusVariant = (s: Objective['status']) =>
    s === 'completed' ? 'default' : s === 'active' ? 'secondary' : s === 'archived' ? 'outline' : 'outline';

  return (
    <div className="mx-auto max-w-4xl space-y-6 py-2">
      <div className="flex items-center gap-3">
        <Button
          variant="ghost"
          size="sm"
          onClick={() => navigate('/dashboard/project-management')}
        >
          <ArrowLeft className="mr-2 h-4 w-4" />
          Kembali
        </Button>
      </div>

      {projectId && <ProjectWorkspaceNav projectId={projectId} />}

      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Objectives</h1>
          <p className="text-sm text-muted-foreground">
            Tujuan utama proyek Project Management ini.
          </p>
        </div>
        <Button onClick={() => setCreateOpen(true)}>
          <Plus className="mr-2 h-4 w-4" />
          Objective Baru
        </Button>
      </div>

      {error && (
        <Card className="border-destructive/50">
          <CardContent className="py-4 text-sm text-destructive">{error}</CardContent>
        </Card>
      )}

      {loading ? (
        <div className="flex items-center justify-center py-16 text-muted-foreground">
          <Loader2 className="h-6 w-6 animate-spin" />
        </div>
      ) : activeObjectives.length === 0 ? (
        <Card>
          <CardContent className="flex flex-col items-center gap-3 py-16 text-center">
            <Target className="h-10 w-10 text-muted-foreground" />
            <CardTitle className="text-lg">Belum ada Objective</CardTitle>
            <CardDescription>Tambahkan Objective pertama untuk proyek ini.</CardDescription>
            <Button onClick={() => setCreateOpen(true)} className="mt-2">
              <Plus className="mr-2 h-4 w-4" />
              Objective Baru
            </Button>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-3">
          {activeObjectives.map((objective, index) => (
            <Card key={objective.id}>
              <CardContent className="flex items-start justify-between gap-4 py-4">
                <div className="flex-1 space-y-1">
                  <div className="flex items-center gap-2">
                    <CardTitle className="text-base">{objective.title}</CardTitle>
                    <Badge variant={statusVariant(objective.status)}>{objective.status}</Badge>
                  </div>
                  {objective.description && (
                    <p className="text-sm text-muted-foreground">{objective.description}</p>
                  )}
                  {objective.success_criteria && (
                    <p className="text-xs text-muted-foreground">
                      Kriteria sukses: {objective.success_criteria}
                    </p>
                  )}
                </div>
                <div className="flex shrink-0 items-center gap-1">
                  <Button variant="ghost" size="icon" disabled={index === 0} onClick={() => handleMove(index, -1)}>
                    <ArrowUp className="h-4 w-4" />
                  </Button>
                  <Button
                    variant="ghost"
                    size="icon"
                    disabled={index === activeObjectives.length - 1}
                    onClick={() => handleMove(index, 1)}
                  >
                    <ArrowDown className="h-4 w-4" />
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => openEdit(objective)}>
                    Edit
                  </Button>
                  {canDelete && (
                    <Button variant="outline" size="icon" onClick={() => handleArchive(objective)}>
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {archivedObjectives.length > 0 && (
        <div className="space-y-3 pt-4">
          <h2 className="text-sm font-semibold text-muted-foreground">Diarsipkan</h2>
          {archivedObjectives.map((objective) => (
            <Card key={objective.id} className="opacity-70">
              <CardContent className="flex items-center justify-between gap-4 py-4">
                <div className="flex items-center gap-2">
                  <CardTitle className="text-base">{objective.title}</CardTitle>
                  <Badge variant="outline">archived</Badge>
                </div>
                {canDelete && (
                  <Button variant="outline" size="sm" onClick={() => handleRestore(objective)}>
                    <RotateCcw className="mr-2 h-4 w-4" />
                    Kembalikan
                  </Button>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      <Dialog
        open={createOpen || !!editing}
        onOpenChange={(open) => {
          if (!open) {
            setCreateOpen(false);
            setEditing(null);
            resetForm();
          }
        }}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{editing ? 'Edit Objective' : 'Objective Baru'}</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <Label htmlFor="obj-title">Judul</Label>
              <Input id="obj-title" value={title} onChange={(e) => setTitle(e.target.value)} />
            </div>
            <div>
              <Label htmlFor="obj-desc">Deskripsi</Label>
              <Textarea id="obj-desc" value={description} onChange={(e) => setDescription(e.target.value)} />
            </div>
            <div>
              <Label htmlFor="obj-criteria">Kriteria Sukses</Label>
              <Textarea
                id="obj-criteria"
                value={successCriteria}
                onChange={(e) => setSuccessCriteria(e.target.value)}
              />
            </div>
            {editing && (
              <div>
                <Label htmlFor="obj-status">Status</Label>
                <Select value={status} onValueChange={(v) => setStatus(v as typeof status)}>
                  <SelectTrigger id="obj-status">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="draft">Draft</SelectItem>
                    <SelectItem value="active">Active</SelectItem>
                    <SelectItem value="completed">Completed</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            )}
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              disabled={saving}
              onClick={() => {
                setCreateOpen(false);
                setEditing(null);
                resetForm();
              }}
            >
              Batal
            </Button>
            <Button onClick={editing ? handleUpdate : handleCreate} disabled={saving || !title.trim()}>
              {saving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
              Simpan
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
