import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Loader2, History } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { supabase } from '@/integrations/supabase/client';
import { ProjectWorkspaceNav } from '../ProjectWorkspaceNav';

/**
 * PM-3 scope only: read-only Activity Log feed. Newest first, no edit/
 * delete control anywhere -- project_activity_events is append-only at the
 * database layer (INSERT/UPDATE/DELETE revoked from authenticated/anon),
 * this page only ever SELECTs it.
 */
const EVENT_LABELS: Record<string, string> = {
  project_created: 'Proyek dibuat',
  objective_created: 'Objective dibuat',
  objective_updated: 'Objective diperbarui',
  objective_reordered: 'Objective diurutkan ulang',
  objective_archived: 'Objective diarsipkan',
  objective_restored: 'Objective dikembalikan',
  stage_created: 'Stage dibuat',
  stage_updated: 'Stage diperbarui',
  stage_reordered: 'Stage diurutkan ulang',
  stage_status_changed: 'Status Stage berubah',
  stage_archived: 'Stage diarsipkan',
  stage_restored: 'Stage dikembalikan',
  wbs_stage_assigned: 'WBS ditautkan ke Stage',
  wbs_stage_unassigned: 'Tautan WBS ke Stage dilepas',
  wbs_people_changed: 'PIC/Reviewer WBS berubah',
  meal_context_changed: 'Context indikator MEAL diperbarui',
  deliverable_created: 'Deliverable dibuat',
  deliverable_status_changed: 'Status Deliverable berubah',
  deliverable_archived: 'Deliverable diarsipkan',
  deliverable_stage_assigned: 'Deliverable ditautkan ke Stage',
  deliverable_stage_unassigned: 'Tautan Deliverable ke Stage dilepas',
};

const ENTITY_LABELS: Record<string, string> = {
  project: 'Proyek',
  objective: 'Objective',
  stage: 'Stage',
  wbs_item: 'WBS',
  meal_item: 'MEAL',
  deliverable: 'Deliverable',
};

interface ActivityEvent {
  id: string;
  entity_type: string;
  entity_id: string;
  event_type: string;
  safe_metadata: Record<string, unknown>;
  actor_id: string;
  created_at: string;
}

export default function ProjectActivityPage() {
  const { projectId } = useParams<{ projectId: string }>();
  const navigate = useNavigate();

  const [events, setEvents] = useState<ActivityEvent[]>([]);
  const [actorNames, setActorNames] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!projectId) return;
    setLoading(true);
    setError(null);

    // project_activity_events is not yet reflected in the generated
    // Database type (types are Production-canonical and are not
    // regenerated by this change), so this query is narrowly cast.
    (supabase as any)
      .from('project_activity_events')
      .select('id, entity_type, entity_id, event_type, safe_metadata, actor_id, created_at')
      .eq('project_id', projectId)
      .order('created_at', { ascending: false })
      .limit(200)
      .then(async ({ data, error: fetchError }: any) => {
        if (fetchError) {
          setError(fetchError.message);
          setLoading(false);
          return;
        }
        const rows = (data || []) as ActivityEvent[];
        setEvents(rows);

        const actorIds = Array.from(new Set(rows.map((r) => r.actor_id)));
        if (actorIds.length > 0) {
          const { data: profiles } = await supabase
            .from('profiles')
            .select('id, full_name')
            .in('id', actorIds);
          const names: Record<string, string> = {};
          for (const p of profiles || []) {
            names[p.id] = p.full_name || p.id;
          }
          setActorNames(names);
        }
        setLoading(false);
      });
  }, [projectId]);

  const formatMetadata = (metadata: Record<string, unknown>) => {
    const entries = Object.entries(metadata || {});
    if (entries.length === 0) return null;
    return entries.map(([k, v]) => `${k}: ${String(v)}`).join(', ');
  };

  return (
    <div className="mx-auto max-w-4xl space-y-6 py-2">
      <div className="flex items-center gap-3">
        <Button variant="ghost" size="sm" onClick={() => navigate('/dashboard/project-management')}>
          <ArrowLeft className="mr-2 h-4 w-4" />
          Kembali
        </Button>
      </div>

      {projectId && <ProjectWorkspaceNav projectId={projectId} />}

      <div>
        <h1 className="text-2xl font-bold tracking-tight">Activity Log</h1>
        <p className="text-sm text-muted-foreground">Riwayat aktivitas proyek, terbaru di atas. Read-only.</p>
      </div>

      {error && (
        <Card className="border-destructive/50">
          <CardContent className="py-4 text-sm text-destructive">{error}</CardContent>
        </Card>
      )}

      {loading ? (
        <div className="flex items-center justify-center py-16 text-muted-foreground">
          <Loader2 className="h-6 w-6 animate-spin" />
        </div>
      ) : events.length === 0 ? (
        <Card>
          <CardContent className="flex flex-col items-center gap-3 py-16 text-center">
            <History className="h-10 w-10 text-muted-foreground" />
            <p className="text-sm text-muted-foreground">Belum ada aktivitas tercatat.</p>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-2">
          {events.map((event) => (
            <Card key={event.id}>
              <CardContent className="flex items-center justify-between gap-4 py-3">
                <div className="flex items-center gap-3">
                  <Badge variant="outline">{ENTITY_LABELS[event.entity_type] || event.entity_type}</Badge>
                  <div>
                    <p className="text-sm font-medium">{EVENT_LABELS[event.event_type] || event.event_type}</p>
                    <p className="text-xs text-muted-foreground">
                      {actorNames[event.actor_id] || event.actor_id} ·{' '}
                      {new Date(event.created_at).toLocaleString('id-ID')}
                      {formatMetadata(event.safe_metadata) && ` · ${formatMetadata(event.safe_metadata)}`}
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
