import * as fs from 'fs';
import * as path from 'path';
import YAML from 'yaml';

const projDir = 'c:/Users/maula/.gemini/antigravity/scratch/impactory';

// First 14 items are under archetypes:
const existingArchYaml = fs.readFileSync(path.join(projDir, 'ontology/archetypes.yaml'), 'utf-8');

// Let's create a clean 40-item YAML list
const archetypesList = [
  { id: "ARCH-TRAINING-001", archetype_id: "ARCH-TRAINING-001", name: "001 Training & Capacity Building", category: "Capacity", action_signals: ["melatih", "pelatihan", "workshop", "bimtek"], object_signals: ["peserta", "modul", "kurikulum"], status: "ACTIVE" },
  { id: "ARCH-TOT-002", archetype_id: "ARCH-TOT-002", name: "002 Training of Trainers (ToT)", category: "Capacity", action_signals: ["melatih pelatih", "kaderisasi fasilitator"], object_signals: ["master trainer", "kader"], status: "ACTIVE" },
  { id: "ARCH-MENTOR-003", archetype_id: "ARCH-MENTOR-003", name: "003 Coaching & Mentorship", category: "Capacity", action_signals: ["mendampingi", "pendampingan", "coaching"], object_signals: ["mentee", "usaha dampingan"], status: "ACTIVE" },
  { id: "ARCH-FACIL-004", archetype_id: "ARCH-FACIL-004", name: "004 Facilitation & Dialogue", category: "Governance", action_signals: ["memfasilitasi", "musyawarah", "rembug"], object_signals: ["forum warga", "pemdes"], status: "ACTIVE" },
  { id: "ARCH-BCC-005", archetype_id: "ARCH-BCC-005", name: "005 Behavior Change Communication", category: "Awareness", action_signals: ["sosialisasi", "kampanye gizi", "edukasi publik"], object_signals: ["masyarakat", "ibu hamil"], status: "ACTIVE" },
  { id: "ARCH-AWARE-006", archetype_id: "ARCH-AWARE-006", name: "006 Awareness & Sensitization", category: "Awareness", action_signals: ["penyuluhan", "sebar leaflet", "siaran radio"], object_signals: ["warga desa"], status: "ACTIVE" },
  { id: "ARCH-DIGDEV-007", archetype_id: "ARCH-DIGDEV-007", name: "007 Digital & App Development", category: "Digital", action_signals: ["mengembangkan aplikasi", "onboarding digital", "platform online"], object_signals: ["pengguna", "web portal"], status: "ACTIVE" },
  { id: "ARCH-RESEARCH-008", archetype_id: "ARCH-RESEARCH-008", name: "008 Action Research & Policy Diagnostics", category: "Research", action_signals: ["studi kelayakan", "riset aksi", "kajian kebijakan"], object_signals: ["laporan riset", "rekomendasi"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-DASH-009", archetype_id: "ARCH-DASH-009", name: "009 Dashboard & Management Information System", category: "Digital", action_signals: ["sistem informasi", "dashboard pantau"], object_signals: ["mis daerah", "admin"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-EQUIP-010", archetype_id: "ARCH-EQUIP-010", name: "010 Equipment & Tool Provision", category: "Asset", action_signals: ["mencetak", "menyerahkan bantuan alat", "hibah mesin"], object_signals: ["mesin pengolah", "alat tangkap"], status: "ACTIVE" },
  { id: "ARCH-INFRA-011", archetype_id: "ARCH-INFRA-011", name: "011 Small-scale Rural Infrastructure", category: "Infrastructure", action_signals: ["pembangunan sarana", "jalan tani", "irigasi desa"], object_signals: ["infrastruktur fisik"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-GRANTS-012", archetype_id: "ARCH-GRANTS-012", name: "012 Micro-grants & Cash Transfer", category: "Financial", action_signals: ["penyaluran dana hibah", "bantuan modal", "seed funding"], object_signals: ["penerima manfaat"], status: "ACTIVE" },
  { id: "ARCH-A2F-013", archetype_id: "ARCH-A2F-013", name: "013 Access to Finance & Microfinance Linkage", category: "Financial", action_signals: ["linking ke bank", "fasilitasi kredit usaha", "akses pinjaman"], object_signals: ["debitur", "lembaga keuangan"], status: "ACTIVE" },
  { id: "ARCH-INCUB-014", archetype_id: "ARCH-INCUB-014", name: "014 Business Incubation & Acceleration", category: "Economic", action_signals: ["inkubasi bisnis", "akselerasi umkm", "bootcamp wirausaha"], object_signals: ["tenant", "startup"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-MARKET-015", archetype_id: "ARCH-MARKET-015", name: "015 Market Linkage & Buyer Matching", category: "Economic", action_signals: ["menghubungkan ke off-taker", "temu bisnis", "pemasaran bersama"], object_signals: ["pembeli formal", "supermarket"], status: "ACTIVE" },
  { id: "ARCH-VALUECHAIN-016", archetype_id: "ARCH-VALUECHAIN-016", name: "016 Value Chain & Supply Linkage Enhancement", category: "Economic", action_signals: ["rantai pasok", "rantai nilai", "offtaker pasar"], object_signals: ["pemasok", "agregator"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-COOP-017", archetype_id: "ARCH-COOP-017", name: "017 Institutional Cooperative Development", category: "Governance", action_signals: ["penguatan koperasi", "kelembagaan tani", "bumdes"], object_signals: ["pengurus", "anggota"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-CAPACITY-018", archetype_id: "ARCH-CAPACITY-018", name: "018 CSO & Institutional Strengthening", category: "Capacity", action_signals: ["penguatan organisasi", "pelatihan tata kelola", "sop lembaga"], object_signals: ["staf cso", "pengurus lsm"], status: "ACTIVE" },
  { id: "ARCH-POLICY-019", archetype_id: "ARCH-POLICY-019", name: "019 Policy Drafting & Local Regulation", category: "Governance", action_signals: ["menyusun perdes", "drafting ranperda", "policy brief"], object_signals: ["peraturan desa", "sk bupati"], status: "ACTIVE" },
  { id: "ARCH-SERVICE-020", archetype_id: "ARCH-SERVICE-020", name: "020 Direct Service Delivery & Outreach", category: "Service", action_signals: ["layanan langsung", "posyandu keliling", "bantuan sosial"], object_signals: ["warga terpencil"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-REHAB-021", archetype_id: "ARCH-REHAB-021", name: "021 Environmental Restoration & Rehabilitation", category: "Environment", action_signals: ["rehabilitasi lahan", "penanaman mangrove", "restorasi sungai"], object_signals: ["hektar lahan"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-ADVOCACY-022", archetype_id: "ARCH-ADVOCACY-022", name: "022 Policy Advocacy & Campaigning", category: "Governance", action_signals: ["advokasi kebijakan", "kampanye publik", "draft perdes"], object_signals: ["stakeholder kunci"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-SCHOLAR-023", archetype_id: "ARCH-SCHOLAR-023", name: "023 Scholarship & Education Financial Support", category: "Education", action_signals: ["beasiswa sekolah", "bantuan biaya pendidikan"], object_signals: ["siswi kurang mampu"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-CLINIC-024", archetype_id: "ARCH-CLINIC-024", name: "024 Mobile Clinic & Health Screening", category: "Health", action_signals: ["klinik keliling", "pemeriksaan kesehatan gratis"], object_signals: ["pasien terpencil"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-WASTE-025", archetype_id: "ARCH-WASTE-025", name: "025 Community Waste Management & Recycling", category: "Environment", action_signals: ["bank sampah", "daur ulang", "pengolahan sampah"], object_signals: ["nasabah bank sampah"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-WATER-026", archetype_id: "ARCH-WATER-026", name: "026 Clean Water Facility Installation", category: "WASH", action_signals: ["pipanisasi air", "pembangunan pamsimas", "sumur bor"], object_signals: ["kk penerima air"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-ENERGY-027", archetype_id: "ARCH-ENERGY-027", name: "027 Renewable Energy & Solar Installation", category: "Energy", action_signals: ["plts komunal", "panel surya", "biogas"], object_signals: ["unit terpasang"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-PROTECT-028", archetype_id: "ARCH-PROTECT-028", name: "028 Child & Vulnerable Group Protection", category: "Inclusion", action_signals: ["perlindungan anak", "pos pengaduan gbv", "ruang aman"], object_signals: ["korban kekerasan"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-SOCACC-029", archetype_id: "ARCH-SOCACC-029", name: "029 Social Accountability & Community Scorecard", category: "Governance", action_signals: ["citizen report card", "audit sosial", "kotak aduan"], object_signals: ["penyedia layanan"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-NETWORK-030", archetype_id: "ARCH-NETWORK-030", name: "030 Multi-Stakeholder Network Building", category: "Partnership", action_signals: ["jaringan kerja", "mou konsorsium", "forum multi-pihak"], object_signals: ["mitra strategis"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-PEER-031", archetype_id: "ARCH-PEER-031", name: "031 Peer-to-Peer Learning & Exchange Visit", category: "Capacity", action_signals: ["studi banding", "kunjungan antar-petani", "peer learning"], object_signals: ["komunitas belajar"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-FEEDING-032", archetype_id: "ARCH-FEEDING-032", name: "032 Supplementary Nutrition & Feeding Program", category: "Health", action_signals: ["pmt anak stunting", "makanan tambahan ibu hamil"], object_signals: ["balita stunting"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-TECH-033", archetype_id: "ARCH-TECH-033", name: "033 Appropriate Technology Transfer", category: "Technology", action_signals: ["penerapan teknologi tepat guna", "mesin pengolah"], object_signals: ["kelompok tani"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-DEMPLOT-034", archetype_id: "ARCH-DEMPLOT-034", name: "034 Demonstration Plot & Field Trials", category: "Agriculture", action_signals: ["demplot tani", "lahan percontohan", "uji coba varietas"], object_signals: ["petani peserta"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-CERT-035", archetype_id: "ARCH-CERT-035", name: "035 Standards & Product Certification", category: "Economic", action_signals: ["sertifikasi halal", "bpom", "sertifikat organik"], object_signals: ["produk umkm"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-PREPAREDNESS-036", archetype_id: "ARCH-PREPAREDNESS-036", name: "036 Disaster Preparedness & Contingency Plan", category: "Disaster", action_signals: ["menyusun rencana kontinjensi", "simulasi bencana", "drill"], object_signals: ["dokumen kontinjensi", "tim siaga"], status: "ACTIVE" },
  { id: "ARCH-SEED-037", archetype_id: "ARCH-SEED-037", name: "037 High-Quality Seed & Seedling Distribution", category: "Agriculture", action_signals: ["bantuan bibit unggul", "benih tersertifikasi"], object_signals: ["petani penerima"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-MIGRANT-038", archetype_id: "ARCH-MIGRANT-038", name: "038 Migrant Worker Safe Migration & Empowerment", category: "Inclusion", action_signals: ["perekrutan aman", "perlindungan pmi", "desa peduli pmi"], object_signals: ["pekerja migran"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-LEGAL-039", archetype_id: "ARCH-LEGAL-039", name: "039 Legal Aid & Identity Documentation", category: "Governance", action_signals: ["bantuan hukum", "pembuatan akta lahir", "ktp-el"], object_signals: ["warga tanpa akta"], status: "HUMAN_REVIEW_REQUIRED" },
  { id: "ARCH-URBAN-040", archetype_id: "ARCH-URBAN-040", name: "040 Slum Upgrading & Housing Improvement", category: "Urban", action_signals: ["penataan kawasan kumuh", "bedah rumah", "sanitasi komunal"], object_signals: ["kk kawasan kumuh"], status: "HUMAN_REVIEW_REQUIRED" }
];

const yamlString = YAML.stringify(archetypesList);
fs.writeFileSync(path.join(projDir, 'ontology/archetypes.yaml'), `# CANONICAL INTERVENTION ARCHETYPES ONTOLOGY\n# Authority: ADR-0001 Rev 2 & Corpus v1 / v1.1 §17 / §24\n# Total Entries: 40\n\n` + yamlString);

console.log('Cleaned and formatted ontology/archetypes.yaml with 40 entries!');
