import { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Plus, Loader2, FolderKanban } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/providers/AuthProvider';
import { ensureDefaultOrg } from '@/lib/grant-writer/orgHelper';

/**
 * PM-1A scope only: standalone project creation via create_project_management_project
 * and a listing of what's been created. Objective/Stage/WBS/Budget/MEAL/Deliverables
 * workspace views land in later PM phases.
 */
interface ProjectManagementProject {
  id: string;
  name: string;
  status: string | null;
  created_at: string | null;
}

export default function ProjectManagementIndex() {
  const { user, profile } = useAuth();
  const { toast } = useToast();
  const navigate = useNavigate();

  const [projects, setProjects] = useState<ProjectManagementProject[]>([]);
  const [loading, setLoading] = useState(true);
  const [createOpen, setCreateOpen] = useState(false);
  const [creating, setCreating] = useState(false);

  const [name, setName] = useState('');
  const [sector, setSector] = useState('');
  const [location, setLocation] = useState('');
  const [duration, setDuration] = useState('');
  const [startDate, setStartDate] = useState('');
  const [beneficiaryCount, setBeneficiaryCount] = useState('');
  const [beneficiaryDesc, setBeneficiaryDesc] = useState('');

  const loadProjects = useCallback(async () => {
    setLoading(true);
    try {
      const orgId = await ensureDefaultOrg(user!.id, profile?.full_name);

      // project_mode is not yet reflected in the generated Database type
      // (types are Production-canonical and are not regenerated by this change),
      // so this one query is narrowly cast rather than left untyped everywhere.
      const { data, error } = await (supabase.from('lfa_projects') as any)
        .select('id, name, status, created_at')
        .eq('org_id', orgId)
        .eq('project_mode', 'project_management')
        .order('created_at', { ascending: false });

      if (error) throw error;
      setProjects((data || []) as ProjectManagementProject[]);
    } catch (err) {
      const error = err as Error;
      toast({
        title: 'Gagal memuat proyek',
        description: error.message,
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  }, [user, profile, toast]);

  useEffect(() => {
    if (user) {
      void loadProjects();
    }
  }, [user, loadProjects]);

  const resetForm = () => {
    setName('');
    setSector('');
    setLocation('');
    setDuration('');
    setStartDate('');
    setBeneficiaryCount('');
    setBeneficiaryDesc('');
  };

  const handleCreate = async () => {
    if (!name.trim()) return;
    setCreating(true);
    try {
      // Same not-yet-typed-schema reason as loadProjects above.
      const { data, error } = await (supabase.rpc as any)('create_project_management_project', {
        p_name: name.trim(),
        p_sector: sector || null,
        p_location: location || null,
        p_duration_months: duration ? parseInt(duration, 10) : null,
        p_start_date: startDate || null,
        p_beneficiary_count: beneficiaryCount ? parseInt(beneficiaryCount, 10) : null,
        p_beneficiary_description: beneficiaryDesc || null,
      });

      if (error) throw error;

      toast({
        title: 'Proyek Berhasil Dibuat',
        description: 'Proyek Project Management baru telah tercatat.',
      });
      setCreateOpen(false);
      resetForm();
      void loadProjects();
      void data;
    } catch (err) {
      const error = err as Error;
      toast({
        title: 'Gagal membuat proyek',
        description: error.message,
        variant: 'destructive',
      });
    } finally {
      setCreating(false);
    }
  };

  return (
    <div className="mx-auto max-w-6xl space-y-8 py-2">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Project Management</h1>
          <p className="text-sm text-muted-foreground">
            Entry point terpisah untuk proyek non-LFA — Objective, Stage, WBS, Budget, MEAL, dan
            Deliverables yang sama digunakan kembali di sini.
          </p>
        </div>
        <Button onClick={() => setCreateOpen(true)}>
          <Plus className="mr-2 h-4 w-4" />
          Proyek Baru
        </Button>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-16 text-muted-foreground">
          <Loader2 className="h-6 w-6 animate-spin" />
        </div>
      ) : projects.length === 0 ? (
        <Card>
          <CardContent className="flex flex-col items-center gap-3 py-16 text-center">
            <FolderKanban className="h-10 w-10 text-muted-foreground" />
            <CardTitle className="text-lg">Belum ada proyek Project Management</CardTitle>
            <CardDescription>
              Buat proyek baru untuk mulai bekerja tanpa Logical Framework Analysis (LFA).
            </CardDescription>
            <Button onClick={() => setCreateOpen(true)} className="mt-2">
              <Plus className="mr-2 h-4 w-4" />
              Proyek Baru
            </Button>
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {projects.map((p) => (
            <Card
              key={p.id}
              className="cursor-pointer transition-colors hover:border-primary/50"
              onClick={() => navigate(`/dashboard/project-management/${p.id}/objectives`)}
            >
              <CardHeader>
                <CardTitle className="text-base">{p.name}</CardTitle>
                <CardDescription>
                  {p.created_at ? new Date(p.created_at).toLocaleDateString('id-ID') : ''}
                </CardDescription>
              </CardHeader>
              <CardContent>
                <Badge variant="secondary">{p.status || 'draft'}</Badge>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      <Dialog open={createOpen} onOpenChange={setCreateOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Proyek Project Management Baru</DialogTitle>
            <DialogDescription>
              Proyek ini tidak memerlukan LFA Matrix — Anda dapat langsung menyusun WBS secara
              manual setelah proyek dibuat.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <Label htmlFor="pm-name">Nama Proyek</Label>
              <Input id="pm-name" value={name} onChange={(e) => setName(e.target.value)} />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label htmlFor="pm-sector">Sektor</Label>
                <Input id="pm-sector" value={sector} onChange={(e) => setSector(e.target.value)} />
              </div>
              <div>
                <Label htmlFor="pm-location">Lokasi</Label>
                <Input
                  id="pm-location"
                  value={location}
                  onChange={(e) => setLocation(e.target.value)}
                />
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label htmlFor="pm-duration">Durasi (bulan)</Label>
                <Input
                  id="pm-duration"
                  type="number"
                  value={duration}
                  onChange={(e) => setDuration(e.target.value)}
                />
              </div>
              <div>
                <Label htmlFor="pm-start">Tanggal Mulai</Label>
                <Input
                  id="pm-start"
                  type="date"
                  value={startDate}
                  onChange={(e) => setStartDate(e.target.value)}
                />
              </div>
            </div>
            <div>
              <Label htmlFor="pm-beneficiary-count">Jumlah Penerima Manfaat</Label>
              <Input
                id="pm-beneficiary-count"
                type="number"
                value={beneficiaryCount}
                onChange={(e) => setBeneficiaryCount(e.target.value)}
              />
            </div>
            <div>
              <Label htmlFor="pm-beneficiary-desc">Deskripsi Penerima Manfaat</Label>
              <Textarea
                id="pm-beneficiary-desc"
                value={beneficiaryDesc}
                onChange={(e) => setBeneficiaryDesc(e.target.value)}
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setCreateOpen(false)} disabled={creating}>
              Batal
            </Button>
            <Button onClick={handleCreate} disabled={creating || !name.trim()}>
              {creating ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
              Buat Proyek
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
