import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Megaphone, Sparkles, Wand2, AlertTriangle, ChevronDown } from 'lucide-react';
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/components/ui/collapsible';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { cn } from '@/lib/utils';
import {
  type AdBrief,
  type AdObjective,
  type AdPlatform,
  type AdTone,
  OBJECTIVE_LABEL,
  PLATFORM_DESC,
  PLATFORM_LABEL,
  TONE_DESC,
  TONE_LABEL,
} from '@/lib/ads/types';
import { generateAdVariants, type PlatformResult } from '@/lib/ads/generator';
import { generateAds } from '@/lib/ads/ai';
import { useToast } from '@/hooks/use-toast';
import { AdVariantCard } from '@/components/ads/AdVariantCard';

const PLATFORMS: AdPlatform[] = ['meta', 'google', 'tiktok'];
const OBJECTIVES: AdObjective[] = [
  'donasi',
  'awareness',
  'recruit_relawan',
  'event_signup',
  'sales_umkm',
];
const TONES: AdTone[] = ['emosional', 'profesional', 'casual'];

const SAMPLE_BRIEF: AdBrief = {
  campaign: 'Sekolah Adat Sokola',
  message:
    'Pendidikan dasar adaptif untuk anak-anak komunitas adat di pedalaman Indonesia.',
  audience: 'donatur individu usia 25-45',
  region: 'Jakarta & Surabaya',
  objective: 'donasi',
  tone: 'emosional',
  platforms: ['meta', 'tiktok'],
};

const CAMPAIGN_FORMULA_STEPS = [
  {
    title: 'Problem',
    description: 'Masalah apa yang ingin diselesaikan dan kenapa sekarang penting?',
  },
  {
    title: 'Person',
    description: 'Siapa penerima manfaat atau audiens yang menjadi pusat cerita?',
  },
  {
    title: 'Proof',
    description: 'Bukti impact, data program, atau dokumentasi apa yang mendukung campaign?',
  },
  {
    title: 'Plan',
    description: 'Apa rencana aksi, target, dan penggunaan dana/dukungan?',
  },
  {
    title: 'Participation',
    description: 'Apa tindakan konkret yang diminta dari donor, relawan, atau partner?',
  },
];

const TRUST_GUARDRAILS = [
  {
    title: 'Draft, bukan final',
    description:
      'Output Campaign Builder adalah draft campaign yang perlu direview sebelum dipublikasikan.',
  },
  {
    title: 'No Unsupported Claims',
    description: 'Jangan klaim hasil, conversion, atau impact yang tidak punya data pendukung.',
  },
  {
    title: 'Human Review Required',
    description:
      'Cerita penerima manfaat, angka impact, dan CTA harus dicek manusia sebelum dipakai.',
  },
  {
    title: 'Editable Campaign',
    description:
      'Copy yang dihasilkan harus bisa diedit sesuai channel, audiens, dan konteks organisasi.',
  },
];

const WORKFLOW_CONNECTIONS = [
  {
    title: 'Impact Library',
    description:
      'Gunakan cerita penerima manfaat, dokumentasi, laporan impact, dan data program sebagai proof.',
    cta: 'Buka Impact Library',
    href: '/dashboard/impactory-library',
  },
  {
    title: 'Grantwriter',
    description: 'Ambil narasi program, problem statement, dan outcome dari draft proposal.',
    cta: 'Buka Grantwriter',
    href: '/dashboard/grant-writer',
  },
  {
    title: 'Grant Pipeline',
    description:
      'Sesuaikan campaign dengan grant, funder, atau program prioritas yang sedang dikejar.',
    cta: 'Buka Grant Pipeline',
    href: '/dashboard/grantfinder',
  },
  {
    title: 'Readiness Scorecard',
    description: 'Cek apakah sistem dasar organisasi sudah cukup siap sebelum scale campaign.',
    cta: 'Cek Readiness',
    href: '/dashboard/readiness',
  },
];

const CLAIM_SAFETY_RULES = [
  'Jangan mengarang cerita penerima manfaat.',
  'Jangan memakai foto/cerita tanpa izin.',
  'Jangan membuat klaim performa iklan tanpa data.',
  'Jangan menyebut angka impact jika belum diverifikasi.',
  'Pastikan CTA sesuai kapasitas program.',
];

// Source of the variants currently shown on screen.
// 'ai'      -> generated by the ads-generate edge function (real AI output).
// 'sample'  -> deterministic local template loaded via "Coba contoh" - NOT AI.
// 'partial' -> some platforms succeeded with AI but at least one failed; the
//             failed platforms are shown as empty placeholders, not template.
type ResultsSource = 'ai' | 'sample' | 'partial' | null;

export default function ImpactoryAds() {
  const { toast } = useToast();
  const [brief, setBrief] = useState<AdBrief>({
    campaign: '',
    message: '',
    audience: '',
    region: '',
    objective: 'donasi',
    tone: 'emosional',
    platforms: ['meta'],
  });
  const [results, setResults] = useState<PlatformResult[] | null>(null);
  const [resultsSource, setResultsSource] = useState<ResultsSource>(null);
  const [failedPlatforms, setFailedPlatforms] = useState<AdPlatform[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);

  const update = <K extends keyof AdBrief>(key: K, value: AdBrief[K]) =>
    setBrief((p) => ({ ...p, [key]: value }));

  const togglePlatform = (p: AdPlatform) =>
    setBrief((prev) => ({
      ...prev,
      platforms: prev.platforms.includes(p)
        ? prev.platforms.filter((x) => x !== p)
        : [...prev.platforms, p],
    }));

  const canGenerate =
    brief.campaign.trim() &&
    brief.message.trim() &&
    brief.audience.trim() &&
    brief.platforms.length > 0;

  const onGenerate = async () => {
    if (!canGenerate) return;
    setIsGenerating(true);
    try {
      const newResults: PlatformResult[] = [];
      const failed: AdPlatform[] = [];
      const errorMessages: string[] = [];

      for (const p of brief.platforms) {
        const { used, variants, error } = await generateAds({
          campaign: brief.campaign,
          product_or_cause: brief.campaign,
          audience: brief.audience,
          goal: brief.objective,
          platform: p,
          tone: brief.tone,
          key_points: [
            brief.message,
            ...(brief.region ? [`Fokus area: ${brief.region}`] : []),
          ],
          variant_count: 3,
        });

        if (error || !used || variants.length === 0) {
          console.error(`[ads] Edge function failed for ${p}:`, error || 'unknown error');
          failed.push(p);
          if (error) errorMessages.push(`${p}: ${error}`);
          // Do NOT silently substitute template variants. Push an empty
          // platform entry so the UI can show a clear failure state.
          newResults.push({ platform: p, variants: [] });
        } else {
          newResults.push({
            platform: p,
            variants: variants.map((v, i) => ({
              id: `${p}-ai-${i}-${Date.now()}`,
              headline: v.headline,
              body: v.body,
              cta: v.cta,
              hashtags: v.hashtags,
            })),
          });
        }
      }

      setResults(newResults);
      setFailedPlatforms(failed);

      if (failed.length === brief.platforms.length) {
        setResultsSource(null);
        toast({
          title: 'Gagal membuat varian iklan',
          description:
            errorMessages[0] ??
            'Koneksi ke Azure Foundry gagal. Silakan coba lagi.',
          variant: 'destructive',
        });
      } else if (failed.length > 0) {
        setResultsSource('partial');
        toast({
          title: 'Sebagian platform gagal',
          description: `${failed.length} dari ${brief.platforms.length} platform gagal: ${failed.join(', ')}.`,
          variant: 'destructive',
        });
      } else {
        setResultsSource('ai');
        toast({
          title: 'Varian Iklan Berhasil Dibuat',
          description: 'Dihasilkan oleh AI (Azure Foundry).',
        });
      }
    } finally {
      setIsGenerating(false);
    }
  };

  const onLoadSample = () => {
    setBrief(SAMPLE_BRIEF);
    setResults(generateAdVariants(SAMPLE_BRIEF));
    setResultsSource('sample');
    setFailedPlatforms([]);
  };

  return (
    <div className="mx-auto max-w-6xl space-y-6">
      <Card className="relative overflow-hidden border-accent/20 bg-gradient-to-br from-accent-soft/60 via-background to-background p-6 shadow-card md:p-8">
        <div
          aria-hidden
          className="pointer-events-none absolute -right-20 -top-20 h-56 w-56 rounded-full bg-gradient-to-br from-accent/25 to-primary/10 blur-3xl"
        />
        <div className="relative flex flex-wrap items-center gap-4">
          <div className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-accent text-accent-foreground shadow-elegant md:h-14 md:w-14">
            <Megaphone className="h-6 w-6 md:h-7 md:w-7" />
          </div>
          <div className="flex-1 space-y-1">
            <Badge className="bg-accent/15 text-accent hover:bg-accent/20 border-accent/30">
              <Sparkles className="mr-1 h-3 w-3" /> Traction Engine
            </Badge>
            <h1 className="text-h1">Campaign Builder</h1>
            <p className="max-w-2xl text-sm text-muted-foreground md:text-base">
              Bangun campaign brief, copy iklan, CTA, dan follow-up untuk fundraising,
              advokasi, dan growth.
            </p>
          </div>
          <Button variant="outline" size="sm" onClick={onLoadSample} className="gap-1.5">
            <Wand2 className="h-3.5 w-3.5" /> Coba contoh
          </Button>
        </div>
      </Card>

      <div className="grid gap-6 lg:grid-cols-[360px_1fr]">
        <aside className="lg:sticky lg:top-4 lg:self-start">
          <Card className="space-y-5 p-5 shadow-card md:p-6">
            <div className="space-y-1">
              <h2 className="text-base font-semibold">Campaign brief</h2>
              <p className="text-xs text-muted-foreground">
                Isi problem, pesan utama, audiens, dan channel agar draft campaign lebih terarah.
              </p>
            </div>

            <div className="rounded-xl border bg-muted/30 p-3 text-xs leading-relaxed text-muted-foreground">
              <p className="font-semibold text-foreground">
                Brief yang jelas menghasilkan campaign yang lebih kuat
              </p>
              <p className="mt-1">
                Isi campaign/program, tujuan, audiens, pesan utama, channel, dan tone dengan
                spesifik. Semakin jelas brief, semakin mudah draft direview dan disesuaikan.
              </p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="campaign">
                Kampanye / Program <span className="text-destructive">*</span>
              </Label>
              <Input
                id="campaign"
                value={brief.campaign}
                onChange={(e) => update('campaign', e.target.value)}
                placeholder="Mis. Sekolah Adat Sokola"
              />
            </div>

            <div className="space-y-2">
              <Label>Tujuan</Label>
              <Select
                value={brief.objective}
                onValueChange={(v) => update('objective', v as AdObjective)}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {OBJECTIVES.map((o) => (
                    <SelectItem key={o} value={o}>
                      {OBJECTIVE_LABEL[o]}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>
                Platform <span className="text-destructive">*</span>
                <span className="ml-1 text-[10px] font-normal text-muted-foreground">
                  (bisa pilih lebih dari satu)
                </span>
              </Label>
              <div className="grid grid-cols-3 gap-2">
                {PLATFORMS.map((p) => {
                  const active = brief.platforms.includes(p);
                  return (
                    <button
                      key={p}
                      type="button"
                      onClick={() => togglePlatform(p)}
                      aria-pressed={active}
                      className={cn(
                        'rounded-lg border-2 px-3 py-2.5 text-xs font-semibold transition-all',
                        active
                          ? 'border-accent bg-accent text-accent-foreground shadow-sm'
                          : 'border-border bg-card text-foreground hover:border-accent/40 hover:bg-accent/5',
                      )}
                    >
                      {PLATFORM_LABEL[p].split(' ')[0]}
                    </button>
                  );
                })}
              </div>
              {brief.platforms.length > 0 && (
                <p className="text-[11px] text-muted-foreground">
                  {brief.platforms.map((p) => PLATFORM_DESC[p]).join(' / ')}
                </p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="audience">
                Target audiens <span className="text-destructive">*</span>
              </Label>
              <Input
                id="audience"
                value={brief.audience}
                onChange={(e) => update('audience', e.target.value)}
                placeholder="Mis. donatur individu usia 25-45"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="region">Lokasi (opsional)</Label>
              <Input
                id="region"
                value={brief.region ?? ''}
                onChange={(e) => update('region', e.target.value)}
                placeholder="Mis. Jakarta & Surabaya"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="message">
                Pesan utama <span className="text-destructive">*</span>
              </Label>
              <Textarea
                id="message"
                value={brief.message}
                onChange={(e) => update('message', e.target.value)}
                placeholder="Inti pesan: apa yang ditawarkan / masalah yang diselesaikan?"
                rows={3}
              />
            </div>

            <div className="space-y-2">
              <Label>Tone</Label>
              <RadioGroup
                value={brief.tone}
                onValueChange={(v) => update('tone', v as AdTone)}
                className="grid gap-2"
              >
                {TONES.map((t) => {
                  const active = brief.tone === t;
                  return (
                    <label
                      key={t}
                      htmlFor={`tone-${t}`}
                      className={cn(
                        'flex cursor-pointer items-start gap-3 rounded-lg border-2 p-3 transition-all',
                        active
                          ? 'border-accent bg-accent/5'
                          : 'border-border hover:border-accent/40 hover:bg-muted/40',
                      )}
                    >
                      <RadioGroupItem id={`tone-${t}`} value={t} className="mt-0.5" />
                      <div className="flex-1 space-y-0.5">
                        <p className="text-sm font-semibold">{TONE_LABEL[t]}</p>
                        <p className="text-[11px] text-muted-foreground">{TONE_DESC[t]}</p>
                      </div>
                    </label>
                  );
                })}
              </RadioGroup>
            </div>

            <Button
              onClick={onGenerate}
              disabled={!canGenerate || isGenerating}
              size="lg"
              className="w-full bg-accent text-accent-foreground hover:bg-accent/90"
            >
              {isGenerating ? (
                <>
                  <Wand2 className="mr-2 h-4 w-4 animate-spin" />
                  Menyusun draft...
                </>
              ) : (
                <>
                  <Sparkles className="mr-2 h-4 w-4" />
                  Generate Campaign Draft
                </>
              )}
            </Button>

            {/* The one thing worth saying at the moment of generating. The full
                rules live in the guide below; repeating them all here would put
                us back where we started. */}
            <p className="flex items-start gap-1.5 text-[11px] leading-relaxed text-muted-foreground">
              <AlertTriangle className="mt-0.5 h-3 w-3 shrink-0 text-amber-500" />
              <span>
                Hasilnya draft. Periksa setiap angka impact dan cerita penerima manfaat sebelum
                dipublikasikan.
              </span>
            </p>
          </Card>
        </aside>

        <div className="space-y-6">
          {!results ? (
            <Card className="flex flex-col items-center justify-center gap-3 p-12 text-center shadow-card">
              <div className="inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-accent/10 text-accent">
                <Megaphone className="h-7 w-7" />
              </div>
              <div className="space-y-1">
                <p className="font-semibold">Belum ada draft campaign</p>
                <p className="max-w-md text-sm text-muted-foreground">
                  Isi brief di kiri/atas, pilih channel dan tone, lalu generate draft campaign.
                  Mulai dari satu campaign yang jelas sebelum membuat banyak varian.
                </p>
              </div>
              <Button variant="outline" size="sm" onClick={onLoadSample} className="gap-1.5">
                <Wand2 className="h-3.5 w-3.5" /> Coba contoh
              </Button>
            </Card>
          ) : (
            <>
              <Card className="space-y-1 border-primary/15 bg-primary/5 p-4 shadow-card">
                <h2 className="text-base font-semibold">Draft campaign untuk direview</h2>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  Gunakan output ini sebagai draft awal. Sesuaikan channel, audiens, visual, CTA,
                  dan data impact sebelum dipublikasikan.
                </p>
              </Card>
              {resultsSource === 'sample' && (
                <div className="flex items-start gap-2 rounded-lg border border-dashed border-border bg-muted/30 p-3 text-xs text-muted-foreground">
                  <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />
                  <span>
                    <strong className="text-foreground">Contoh statis (bukan AI).</strong>{' '}
                    Varian di bawah dimuat dari template lokal sebagai pratinjau.
                    Klik <strong>Generate Campaign Draft</strong> untuk hasil AI nyata.
                  </span>
                </div>
              )}
              {resultsSource === 'partial' && failedPlatforms.length > 0 && (
                <div className="flex items-start gap-2 rounded-lg border border-destructive/40 bg-destructive/5 p-3 text-xs text-destructive">
                  <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
                  <span>
                    <strong>Sebagian platform gagal:</strong>{' '}
                    {failedPlatforms.join(', ')}. Coba lagi untuk platform tersebut.
                  </span>
                </div>
              )}
              <div className="flex flex-wrap items-center justify-between gap-2">
                <p className="text-sm text-muted-foreground">
                  <strong className="text-foreground">{results.length}</strong> platform /{' '}
                  <strong className="text-foreground">
                    {results.reduce((acc, r) => acc + r.variants.length, 0)}
                  </strong>{' '}
                  varian / tone {TONE_LABEL[brief.tone]} / {OBJECTIVE_LABEL[brief.objective]}
                </p>
                <Button size="sm" variant="ghost" onClick={onGenerate} disabled={isGenerating} className="text-xs">
                  {isGenerating ? <Wand2 className="mr-1 h-3.5 w-3.5 animate-spin" /> : <Sparkles className="mr-1 h-3.5 w-3.5" />}
                  Regenerate
                </Button>
              </div>
              {results.map((res) => (
                <section key={res.platform} className="space-y-3">
                  <div className="flex items-center gap-2">
                    <Badge className="bg-accent/15 text-accent hover:bg-accent/20 border-accent/30">
                      {PLATFORM_LABEL[res.platform]}
                    </Badge>
                    <span className="text-xs text-muted-foreground">
                      {PLATFORM_DESC[res.platform]}
                    </span>
                    {failedPlatforms.includes(res.platform) && (
                      <Badge variant="destructive" className="gap-1 text-[10px]">
                        <AlertTriangle className="h-3 w-3" /> Gagal
                      </Badge>
                    )}
                  </div>
                  {res.variants.length === 0 ? (
                    <Card className="p-4 text-xs text-muted-foreground">
                      Tidak ada varian untuk platform ini. Coba klik{' '}
                      <strong>Regenerate</strong> atau hapus platform dari brief.
                    </Card>
                  ) : (
                    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
                      {res.variants.map((v, i) => (
                        <AdVariantCard
                          key={v.id}
                          variant={v}
                          index={i}
                          platform={res.platform}
                          brief={brief}
                        />
                      ))}
                    </div>
                  )}
                </section>
              ))}
            </>
          )}
        </div>
      </div>

      {/* Panduan — dilipat secara bawaan.
          Sebelumnya sembilan belas kartu penjelasan berdiri di antara judul
          halaman dan formulir, jadi pengguna harus menggulir hampir dua ribu
          piksel sebelum bisa mengetik apa pun. Isinya bagus, tempatnya salah:
          ini rujukan yang dibaca sekali, bukan langkah yang dilalui setiap
          kali. */}
      <Collapsible>
        <Card className="p-4 shadow-card md:p-5">
          <CollapsibleTrigger className="group flex w-full items-center justify-between gap-3 text-left">
            <div className="space-y-0.5">
              <h2 className="text-sm font-bold">Panduan menyusun campaign yang kuat</h2>
              <p className="text-xs text-muted-foreground">
                Formula lima langkah, prinsip draft, dan aturan klaim yang aman.
              </p>
            </div>
            <ChevronDown className="h-4 w-4 shrink-0 text-muted-foreground transition-transform group-data-[state=open]:rotate-180" />
          </CollapsibleTrigger>

          <CollapsibleContent className="space-y-6 pt-5">
            <div className="space-y-3">
              <div className="flex flex-wrap items-center gap-1.5 text-sm font-bold">
                {CAMPAIGN_FORMULA_STEPS.map((step, index) => (
                  <span key={step.title} className="flex items-center gap-1.5">
                    <span className="text-accent">{step.title}</span>
                    {index < CAMPAIGN_FORMULA_STEPS.length - 1 && (
                      <span className="text-muted-foreground/40">&rarr;</span>
                    )}
                  </span>
                ))}
              </div>
              <dl className="grid gap-x-6 gap-y-2 sm:grid-cols-2">
                {CAMPAIGN_FORMULA_STEPS.map((step) => (
                  <div key={step.title} className="text-xs leading-relaxed">
                    <dt className="inline font-semibold text-foreground">{step.title}. </dt>
                    <dd className="inline text-muted-foreground">{step.description}</dd>
                  </div>
                ))}
              </dl>
              <p className="border-l-2 border-accent/40 pl-3 text-xs italic leading-relaxed text-muted-foreground">
                Orang tidak bergerak karena organisasi butuh dana. Orang bergerak karena mereka
                percaya tindakannya menghasilkan perubahan.
              </p>
            </div>

            <div className="space-y-2">
              <h3 className="text-xs font-bold uppercase tracking-wide text-muted-foreground">
                Prinsip output
              </h3>
              <dl className="grid gap-x-6 gap-y-2 sm:grid-cols-2">
                {TRUST_GUARDRAILS.map((item) => (
                  <div key={item.title} className="text-xs leading-relaxed">
                    <dt className="inline font-semibold text-foreground">{item.title}. </dt>
                    <dd className="inline text-muted-foreground">{item.description}</dd>
                  </div>
                ))}
              </dl>
            </div>

            <div className="space-y-2 rounded-xl border border-amber-500/25 bg-amber-500/5 p-4">
              <h3 className="flex items-center gap-1.5 text-xs font-bold text-amber-700 dark:text-amber-500">
                <AlertTriangle className="h-3.5 w-3.5" /> Aturan klaim
              </h3>
              <ul className="space-y-1">
                {CLAIM_SAFETY_RULES.map((rule) => (
                  <li key={rule} className="flex gap-2 text-xs leading-relaxed text-muted-foreground">
                    <span className="text-amber-600">&bull;</span>
                    <span>{rule}</span>
                  </li>
                ))}
              </ul>
            </div>
          </CollapsibleContent>
        </Card>
      </Collapsible>

      {/* Sumber bahan — dulu empat kartu penuh, sekarang empat tautan.
          Isinya memang cuma tautan; kartu setinggi seratus piksel untuk satu
          tautan hanya menambah jarak menuju hal berikutnya. */}
      <Card className="space-y-3 p-4 shadow-card md:p-5">
        <div className="space-y-0.5">
          <h2 className="text-sm font-bold">Ambil bahan campaign dari modul lain</h2>
          <p className="text-xs text-muted-foreground">
            Impact Library untuk bukti, Grantwriter untuk narasi program, Grant Pipeline untuk
            menyelaraskan dengan funder.
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          {WORKFLOW_CONNECTIONS.map((item) => (
            <Button
              key={item.title}
              asChild
              variant="outline"
              size="sm"
              className="gap-1.5 text-xs"
              title={item.description}
            >
              <Link to={item.href}>
                {item.title}
                <ArrowRight className="h-3.5 w-3.5" />
              </Link>
            </Button>
          ))}
        </div>
      </Card>
    </div>
  );
}
