import { useState } from 'react';
import { Megaphone, Sparkles, Wand2, AlertTriangle } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { cn } from '@/lib/utils';
import {
  type AdBrief,
  type AdObjective,
  type AdPlatform,
  type AdTone,
  OBJECTIVE_LABEL,
  PLATFORM_DESC,
  PLATFORM_LABEL,
  TONE_DESC,
  TONE_LABEL,
} from '@/lib/ads/types';
import { generateAdVariants, type PlatformResult } from '@/lib/ads/generator';
import { generateAds } from '@/lib/ads/ai';
import { useToast } from '@/hooks/use-toast';
import { AdVariantCard } from '@/components/ads/AdVariantCard';

const PLATFORMS: AdPlatform[] = ['meta', 'google', 'tiktok'];
const OBJECTIVES: AdObjective[] = [
  'donasi',
  'awareness',
  'recruit_relawan',
  'event_signup',
  'sales_umkm',
];
const TONES: AdTone[] = ['emosional', 'profesional', 'casual'];

const SAMPLE_BRIEF: AdBrief = {
  campaign: 'Sekolah Adat Sokola',
  message:
    'Pendidikan dasar adaptif untuk anak-anak komunitas adat di pedalaman Indonesia.',
  audience: 'donatur individu usia 25-45',
  region: 'Jakarta & Surabaya',
  objective: 'donasi',
  tone: 'emosional',
  platforms: ['meta', 'tiktok'],
};

// Source of the variants currently shown on screen.
// 'ai'      -> generated by the ads-generate edge function (real AI output).
// 'sample'  -> deterministic local template loaded via "Coba contoh" - NOT AI.
// 'partial' -> some platforms succeeded with AI but at least one failed; the
//             failed platforms are shown as empty placeholders, not template.
type ResultsSource = 'ai' | 'sample' | 'partial' | null;

export default function ImpactoryAds() {
  const { toast } = useToast();
  const [brief, setBrief] = useState<AdBrief>({
    campaign: '',
    message: '',
    audience: '',
    region: '',
    objective: 'donasi',
    tone: 'emosional',
    platforms: ['meta'],
  });
  const [results, setResults] = useState<PlatformResult[] | null>(null);
  const [resultsSource, setResultsSource] = useState<ResultsSource>(null);
  const [failedPlatforms, setFailedPlatforms] = useState<AdPlatform[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);

  const update = <K extends keyof AdBrief>(key: K, value: AdBrief[K]) =>
    setBrief((p) => ({ ...p, [key]: value }));

  const togglePlatform = (p: AdPlatform) =>
    setBrief((prev) => ({
      ...prev,
      platforms: prev.platforms.includes(p)
        ? prev.platforms.filter((x) => x !== p)
        : [...prev.platforms, p],
    }));

  const canGenerate =
    brief.campaign.trim() &&
    brief.message.trim() &&
    brief.audience.trim() &&
    brief.platforms.length > 0;

  const onGenerate = async () => {
    if (!canGenerate) return;
    setIsGenerating(true);
    try {
      const newResults: PlatformResult[] = [];
      const failed: AdPlatform[] = [];
      const errorMessages: string[] = [];

      for (const p of brief.platforms) {
        const { used, variants, error } = await generateAds({
          campaign: brief.campaign,
          product_or_cause: brief.campaign,
          audience: brief.audience,
          goal: brief.objective,
          platform: p,
          tone: brief.tone,
          key_points: [
            brief.message,
            ...(brief.region ? [`Fokus area: ${brief.region}`] : []),
          ],
          variant_count: 3,
        });

        if (error || !used || variants.length === 0) {
          console.error(`[ads] Edge function failed for ${p}:`, error);
          failed.push(p);
          if (error) errorMessages.push(`${p}: ${error}`);
          // Do NOT silently substitute template variants. Push an empty
          // platform entry so the UI can show a clear failure state.
          newResults.push({ platform: p, variants: [] });
        } else {
          newResults.push({
            platform: p,
            variants: variants.map((v, i) => ({
              ...v,
              id: `${p}-ai-${i}-${Date.now()}`,
            })) as any,
          });
        }
      }

      setResults(newResults);
      setFailedPlatforms(failed);

      if (failed.length === brief.platforms.length) {
        setResultsSource(null);
        toast({
          title: 'Gagal membuat varian iklan',
          description:
            errorMessages[0] ??
            'Koneksi ke Azure Foundry gagal. Silakan coba lagi.',
          variant: 'destructive',
        });
      } else if (failed.length > 0) {
        setResultsSource('partial');
        toast({
          title: 'Sebagian platform gagal',
          description: `${failed.length} dari ${brief.platforms.length} platform gagal: ${failed.join(', ')}.`,
          variant: 'destructive',
        });
      } else {
        setResultsSource('ai');
        toast({
          title: 'Varian Iklan Berhasil Dibuat',
          description: 'Dihasilkan oleh AI (Azure Foundry).',
        });
      }
    } finally {
      setIsGenerating(false);
    }
  };

  const onLoadSample = () => {
    setBrief(SAMPLE_BRIEF);
    setResults(generateAdVariants(SAMPLE_BRIEF));
    setResultsSource('sample');
    setFailedPlatforms([]);
  };

  return (
    <div className="mx-auto max-w-6xl space-y-6">
      <Card className="relative overflow-hidden border-accent/20 bg-gradient-to-br from-accent-soft/60 via-background to-background p-6 shadow-card md:p-8">
        <div
          aria-hidden
          className="pointer-events-none absolute -right-20 -top-20 h-56 w-56 rounded-full bg-gradient-to-br from-accent/25 to-primary/10 blur-3xl"
        />
        <div className="relative flex flex-wrap items-center gap-4">
          <div className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-accent text-accent-foreground shadow-elegant md:h-14 md:w-14">
            <Megaphone className="h-6 w-6 md:h-7 md:w-7" />
          </div>
          <div className="flex-1 space-y-1">
            <Badge className="bg-accent/15 text-accent hover:bg-accent/20 border-accent/30">
              <Sparkles className="mr-1 h-3 w-3" /> Generator copy iklan
            </Badge>
            <h1 className="text-h1">Ads</h1>
            <p className="max-w-2xl text-sm text-muted-foreground md:text-base">
              Buat varian copy siap pakai untuk Meta, Google, dan TikTok -
              dirancang untuk kampanye fundraising, advokasi, dan UMKM sosial.
            </p>
          </div>
          <Button variant="outline" size="sm" onClick={onLoadSample} className="gap-1.5">
            <Wand2 className="h-3.5 w-3.5" /> Coba contoh
          </Button>
        </div>
      </Card>

      <div className="grid gap-6 lg:grid-cols-[360px_1fr]">
        <aside className="lg:sticky lg:top-4 lg:self-start">
          <Card className="space-y-5 p-5 shadow-card md:p-6">
            <div className="space-y-1">
              <h2 className="text-base font-semibold">Brief kampanye</h2>
              <p className="text-xs text-muted-foreground">
                Isi minimal kampanye, pesan utama, audiens, dan pilih platform.
              </p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="campaign">
                Kampanye / Program <span className="text-destructive">*</span>
              </Label>
              <Input
                id="campaign"
                value={brief.campaign}
                onChange={(e) => update('campaign', e.target.value)}
                placeholder="Mis. Sekolah Adat Sokola"
              />
            </div>

            <div className="space-y-2">
              <Label>Tujuan</Label>
              <Select
                value={brief.objective}
                onValueChange={(v) => update('objective', v as AdObjective)}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {OBJECTIVES.map((o) => (
                    <SelectItem key={o} value={o}>
                      {OBJECTIVE_LABEL[o]}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>
                Platform <span className="text-destructive">*</span>
                <span className="ml-1 text-[10px] font-normal text-muted-foreground">
                  (bisa pilih lebih dari satu)
                </span>
              </Label>
              <div className="grid grid-cols-3 gap-2">
                {PLATFORMS.map((p) => {
                  const active = brief.platforms.includes(p);
                  return (
                    <button
                      key={p}
                      type="button"
                      onClick={() => togglePlatform(p)}
                      aria-pressed={active}
                      className={cn(
                        'rounded-lg border-2 px-3 py-2.5 text-xs font-semibold transition-all',
                        active
                          ? 'border-accent bg-accent text-accent-foreground shadow-sm'
                          : 'border-border bg-card text-foreground hover:border-accent/40 hover:bg-accent/5',
                      )}
                    >
                      {PLATFORM_LABEL[p].split(' ')[0]}
                    </button>
                  );
                })}
              </div>
              {brief.platforms.length > 0 && (
                <p className="text-[11px] text-muted-foreground">
                  {brief.platforms.map((p) => PLATFORM_DESC[p]).join(' / ')}
                </p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="audience">
                Target audiens <span className="text-destructive">*</span>
              </Label>
              <Input
                id="audience"
                value={brief.audience}
                onChange={(e) => update('audience', e.target.value)}
                placeholder="Mis. donatur individu usia 25-45"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="region">Lokasi (opsional)</Label>
              <Input
                id="region"
                value={brief.region ?? ''}
                onChange={(e) => update('region', e.target.value)}
                placeholder="Mis. Jakarta & Surabaya"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="message">
                Pesan utama <span className="text-destructive">*</span>
              </Label>
              <Textarea
                id="message"
                value={brief.message}
                onChange={(e) => update('message', e.target.value)}
                placeholder="Inti pesan: apa yang ditawarkan / masalah yang diselesaikan?"
                rows={3}
              />
            </div>

            <div className="space-y-2">
              <Label>Tone</Label>
              <RadioGroup
                value={brief.tone}
                onValueChange={(v) => update('tone', v as AdTone)}
                className="grid gap-2"
              >
                {TONES.map((t) => {
                  const active = brief.tone === t;
                  return (
                    <label
                      key={t}
                      htmlFor={`tone-${t}`}
                      className={cn(
                        'flex cursor-pointer items-start gap-3 rounded-lg border-2 p-3 transition-all',
                        active
                          ? 'border-accent bg-accent/5'
                          : 'border-border hover:border-accent/40 hover:bg-muted/40',
                      )}
                    >
                      <RadioGroupItem id={`tone-${t}`} value={t} className="mt-0.5" />
                      <div className="flex-1 space-y-0.5">
                        <p className="text-sm font-semibold">{TONE_LABEL[t]}</p>
                        <p className="text-[11px] text-muted-foreground">{TONE_DESC[t]}</p>
                      </div>
                    </label>
                  );
                })}
              </RadioGroup>
            </div>

            <Button
              onClick={onGenerate}
              disabled={!canGenerate || isGenerating}
              size="lg"
              className="w-full bg-accent text-accent-foreground hover:bg-accent/90"
            >
              {isGenerating ? (
                <>
                  <Wand2 className="mr-2 h-4 w-4 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles className="mr-2 h-4 w-4" />
                  Generate Ad Copy
                </>
              )}
            </Button>
          </Card>
        </aside>

        <div className="space-y-6">
          {!results ? (
            <Card className="flex flex-col items-center justify-center gap-3 p-12 text-center shadow-card">
              <div className="inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-accent/10 text-accent">
                <Megaphone className="h-7 w-7" />
              </div>
              <div className="space-y-1">
                <p className="font-semibold">Belum ada varian</p>
                <p className="max-w-md text-sm text-muted-foreground">
                  Isi brief di kiri lalu klik <strong>Generate Ad Copy</strong>,
                  atau muat contoh untuk lihat hasilnya.
                </p>
              </div>
              <Button variant="outline" size="sm" onClick={onLoadSample} className="gap-1.5">
                <Wand2 className="h-3.5 w-3.5" /> Coba contoh
              </Button>
            </Card>
          ) : (
            <>
              {resultsSource === 'sample' && (
                <div className="flex items-start gap-2 rounded-lg border border-dashed border-border bg-muted/30 p-3 text-xs text-muted-foreground">
                  <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />
                  <span>
                    <strong className="text-foreground">Contoh statis (bukan AI).</strong>{' '}
                    Varian di bawah dimuat dari template lokal sebagai pratinjau.
                    Klik <strong>Generate Ad Copy</strong> untuk hasil AI nyata.
                  </span>
                </div>
              )}
              {resultsSource === 'partial' && failedPlatforms.length > 0 && (
                <div className="flex items-start gap-2 rounded-lg border border-destructive/40 bg-destructive/5 p-3 text-xs text-destructive">
                  <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
                  <span>
                    <strong>Sebagian platform gagal:</strong>{' '}
                    {failedPlatforms.join(', ')}. Coba lagi untuk platform tersebut.
                  </span>
                </div>
              )}
              <div className="flex flex-wrap items-center justify-between gap-2">
                <p className="text-sm text-muted-foreground">
                  <strong className="text-foreground">{results.length}</strong> platform /{' '}
                  <strong className="text-foreground">
                    {results.reduce((acc, r) => acc + r.variants.length, 0)}
                  </strong>{' '}
                  varian / tone {TONE_LABEL[brief.tone]} / {OBJECTIVE_LABEL[brief.objective]}
                </p>
                <Button size="sm" variant="ghost" onClick={onGenerate} disabled={isGenerating} className="text-xs">
                  {isGenerating ? <Wand2 className="mr-1 h-3.5 w-3.5 animate-spin" /> : <Sparkles className="mr-1 h-3.5 w-3.5" />}
                  Regenerate
                </Button>
              </div>
              {results.map((res) => (
                <section key={res.platform} className="space-y-3">
                  <div className="flex items-center gap-2">
                    <Badge className="bg-accent/15 text-accent hover:bg-accent/20 border-accent/30">
                      {PLATFORM_LABEL[res.platform]}
                    </Badge>
                    <span className="text-xs text-muted-foreground">
                      {PLATFORM_DESC[res.platform]}
                    </span>
                    {failedPlatforms.includes(res.platform) && (
                      <Badge variant="destructive" className="gap-1 text-[10px]">
                        <AlertTriangle className="h-3 w-3" /> Gagal
                      </Badge>
                    )}
                  </div>
                  {res.variants.length === 0 ? (
                    <Card className="p-4 text-xs text-muted-foreground">
                      Tidak ada varian untuk platform ini. Coba klik{' '}
                      <strong>Regenerate</strong> atau hapus platform dari brief.
                    </Card>
                  ) : (
                    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
                      {res.variants.map((v, i) => (
                        <AdVariantCard
                          key={v.id}
                          variant={v}
                          index={i}
                          platform={res.platform}
                          brief={brief}
                        />
                      ))}
                    </div>
                  )}
                </section>
              ))}
            </>
          )}
        </div>
      </div>
    </div>
  );
}
